---
title: Números reales
lang: es
---

:::{#exr-supremos-infimos-reales}
$\star$
Para los siguientes subconjuntos de números reales, determinar si están acotados por arriba o por abajo, y en tal caso dar el supremo o el ínfimo.

a. $A = \{-1,0,1\}$
a. $B= [0,1)$
a. $C= (0,\infty)$
a. $D= \left\{1+\frac{1}{n}:n\in\mathbb{N}\right\}$
a. $E= \left\{(-2)^n:n\in\mathbb{N}\right\}$
a. $F= \{x\in\mathbb{R}:x^2-3x+2=0\}$
a. $G= \{x\in\mathbb{R}:x^3-x<0\}$
:::

:::{.callout-tip collapse="true"}
## Solución
a. $A$ está acotado por arriba y por abajo. $\sup(A)=1$ y $\inf(A)=-1$.

a. $B$ está acotado por arriba y por abajo. $\sup(B)=1$ y $\inf(B)=0$.

a. $C$ está acotado por abajo, pero no por arriba. $\inf(C)=0$.

a. $D$ está acotado por arriba y por abajo. $\sup(D)=2$ y $\inf(D)=1$.

a. $E$ no está acotado por arriba ni por abajo.

a. $F$ está acotado por arriba y por abajo. $\sup(F)=2$ y $\inf(F)=1$.

a. $G$ está acotado por arriba pero no por abajo. $\sup(G)=1$.
:::

:::{#exr-supremo-infimo-maximo-minimo-2}
Calcular el supremo y el ínfimo de los siguientes conjuntos. ¿Tienen máximo y mínimo?

a. $A=\{x\in \mathbb{R} : 2 < x^2-2 < 7\}$
b. $B=\{x\in \mathbb{R} : 1 < 4x^2 - 3 \leq 5\}$
:::

:::{.callout-tip collapse="true"}
## Solución
a. $A=(-3,-2)\cup(2,3)$, que como está acotado tiene supremo $\sup(A)=3$ e ínfimo $\inf(A)=-3$. Sin embargo, $3\not \in A$ y $-3\not\in A$, por lo que no tiene ni máximo ni mínimo.

b. $B=[-\sqrt{2},-1)\cup(1,\sqrt{2}]$, que como está acotado tiene supremo $\sup(B)=\sqrt{2}$ e ínfimo $\inf(B)=-\sqrt{2}$. Como además, $-\sqrt{2} \in B$ y $\sqrt{2}\in B$, se tiene que $\max(B)=\sqrt{2}$ y $\min(B)=-\sqrt{2}$.
:::

:::{#exr-supremo-funciones}
Dadas dos funciones $f$ y $g$ ambas con dominio $A\subseteq \mathbb{R}$, demostrar que si sus imágenes están acotadas y $f(a)\leq g(a)$ $\forall a\in A$, entonces $\sup(\operatorname{Im}(f))\leq \sup(\operatorname{Im}(g))$.
:::

:::{.callout-tip collapse="true"}
## Solución
Como las imágenes de $f$ y $g$ están acotadas, y suponiendo que no fuesen vacías, por el axioma del supremo, se tiene que existe $c,d\in\mathbb{R}$ tales que $c=\sup(\operatorname{Im}(f))$ y $d= \sup(\operatorname{Im}(g))$. Como $d$ es el supremo de la imagen de $g$, se tiene que es una cota superior de la imagen de $f$, ya que, para cualquier $a\in A$, se tiene $f(a)\leq g(a)\leq d$. Por consiguiente, tiene que ser $c\leq d$, ya que de lo contrario $c$ no sería el supremo por ser $d$ una cota superior de la imagen de $f$ menor que $c$.
:::

<!-- :::{#exr-no-completitud-racionales}
Demostrar que el conjunto de los números racionales no cumple el axioma de completitud.
::: -->

:::{#exr-cotas-conjunto-opuestos}
Demostrar que si $c\in\mathbb{R}$ es una cota superior de un conjunto $A$, entonces $-c$ es una cota inferior del conjunto de los opuestos $A'=\{-a\in\mathbb{R}: a\in A\}$, y si $c$ es una cota inferior de $A$ entonces $-c$ es una cota superior de $A'$.
:::

:::{.callout-tip collapse="true"}
## Solución
Sea $c\in\mathbb{R}$ una cota superior del conjunto $A$. Entonces, $a\leq c$ $\forall a\in A$. De ello se deduce que para cualquier $a\in A$,

$$
a<c \Rightarrow (-1)a\geq (-1)c \Rightarrow -a\geq -c, 
$$

lo que demuestra que $-c$ es una cota inferior de $A'$.

Del mismo modo, si $c$ una cota inferior del conjunto $A$. Entonces, $c\leq a$ $\forall a\in A$, y de ello se deduce que para cualquier $a\in A$,

$$
c<a \Rightarrow (-1)c\geq (-1)a \Rightarrow -c\geq -a, 
$$

de manera que $-c$ es cota superior de $A'$.
:::

:::{#exr-propiedad-infimo}
$\star$
Demostrar que todo subconjunto no vacío de números reales acotado inferiormente tiene un ínfimo.
:::

:::{.callout-tip collapse="true"}
## Solución


Sea $A\subset\mathbb{R}$ no vacío y acotado inferiormente. Entonces existe un $c\in\mathbb{R}$ que es cota inferior de $A$. Si tomamos ahora el conjunto $A'=\{-a\in\mathbb{R}: a\in A\}$, por el ejercicio @exr-cotas-conjunto-opuestos, se cumple que $-c$ es una cota superior de $A'$. Así pues, $A'$ es un conjunto no vacío y acotado superiormente, y por el axioma del supremo, existe $-s\in\mathbb{R}$ tal que $-s=\sup(A')$.

Veamos ahora que $s$ es el ínfimo de $A$. Como $-s$ es el supremo de $A'$, es una cota superior de $A'$, y por el ejercicio @exr-cotas-conjunto-opuestos, se cumple que $-(-s)=s$ es cota inferior de $A$. Supongamos ahora que existe otra cota inferior $x$ de $A$ tal que $x>s$. Entonces, aplicando una vez más el @exr-cotas-conjunto-opuestos, se tiene que $-x$ es cota superior de $A'$, pero $x>s\Rightarrow (-1)x<(-1)s \Rightarrow -x<-s$, lo que contradice que $-s$ sea el supremo de $A'$, ya que $-x$ sería una cota superior menor que $-s$. Luego $s$ es el ínfimo de $A$.
:::


:::{#exr-propiedad-valor-absoluto}
Demostrar que $|a|-|b|\leq |a-b|$ $\forall a,b\in\mathbb{R}$.
:::

:::{.callout-tip collapse="true"}
## Solución
Veamos todas las posibilidades que pueden darse:

- Si $a=0$, entonces $|a|-|b|= -|b|\leq |-b| = |a-b|$.
- Si $b=0$, entonces $|a|-|b|=|a|= |a-b|$.
- Si $a\geq b>0$, entonces $|a|-|b|=a-b=|a-b|$.
- Si $b\geq a>0$, entonces $|a|-|b|=a-b\leq 0\leq |a-b|$.
- Si $a>0>b$, entonces $|a|-|b| = a-(-b) =a+b < a-b =|a-b|$.
- Si $b>0>a$, entonces $|a|-|b| = -a-b < -a+b = -(a-b) = |a-b|$.
- Si $a\leq b<0$, entonces $|a|-|b| = -a-(-b) = -a+b = -(a-b) = |a-b|$.
- Si $b\leq a<0$, entonces $|a|-|b| = -a-(-b) = -a+b \leq 0 \leq |a-b|$.
:::

:::{#exr-propiedad-arquimediana-1}
$\star$
Usando la propiedad arquimediana de los números reales, demostrar que para cualquier número real $a\in\mathbb{R}$ con $a>0$ existe un número natural $n\in \mathbb{N}$ tal que $0<\frac{1}{n}<a$.Demostrar también que existe otro número natural $m\in \mathbb{N}$ tal que $m-1\leq a< m$. 
:::

:::{.callout-tip collapse="true"}
## Solución
Como $a>0$ se tiene que $\frac{1}{a}>0$, y por la propiedad arquimediana, existe un $n\in\mathbb{N}$ tal que $\frac{1}{a}<n$, de donde se deduce que $\frac{1}{1/a}>\frac{1}{n}>0$, es decir, $0<\frac{1}{n}<a$.

Para demostrar la segunda parte, considérese ahora el conjunto $A=\{k\in \mathbb{N}: a<k\}$. Por la propiedad arquimedana sabemos que existe un $n\in \mathbb{N}$ tal que $a<n$, y por tanto, $n\in A$ por lo que $A$ no está vacío. Aplicando ahora el principio de buena ordenación de los números naturales, como $A\subset \mathbb{N}$, existe un primer elemento $m\in A$, tal que $m-1\not\in A$, de manera que $m-1\leq a$ y con ello se tiene que $m-1\leq a<m$. 
:::

:::{#exr-densidad-racionales}
Se dice que un conjunto $A$ es denso en $\mathbb{R}$ si cada intervalo $(a,b)$ de $\mathbb{R}$ contiene algún elemento de $A$. Demostrar que $\mathbb{Q}$ es denso en $\mathbb{R}$.
:::

:::{.callout-tip collapse="true"}
## Solución
La prueba es la misma que la de la propiedad arquimediana. Basta con tomar $n\in \mathbb{N}$ tal que $\frac{1}{n}< b-a$. Si ahora se toma el primer múltiplo de $1/n$ tal que $a<\frac{m}{n}$, también se cumplirá que $\frac{m}{n}<b$, ya que de lo contrario $\frac{m-1}{n}<a<b<\frac{m}{n}$ lo que lleva a la contradicción de que $\frac{1}{n}>b-a$. 
:::


