---
title: Límites de funciones
lang: es
---

:::{#exr-funcion-constante}
Sea $f(x)=c$ una función constante. Demostrar que $\lim_{x\to a}f(x)=c$ $\forall a\in\mathbb{R}$.  
:::

:::{.callout-tip collapse="true"}
## Solución
Para cualquier $\varepsilon>0$ se puede tomar $\delta = 1$ tal que si $|x-a|<\delta=1$, entonces $|f(x)-c| = |c-c|=0<\varepsilon$.
:::

:::{#exr-definicion-limite}
$\star$
Dada la función $f(x)=4x-10$, demostrar usando la definición de límite que $\lim_{x\to 3}f(x)=2$.  
:::

:::{.callout-tip collapse="true"}
## Solución
Para cualquier $\varepsilon>0$ se puede tomar $\delta = \frac{\varepsilon}{4}$ tal que si $|x-3|<\delta=\frac{\varepsilon}{4}$, entonces 

$$
|f(x)-2| = |4x-10-2|= |4x-12| = 4|x-3|<4\frac{\varepsilon}{4} =\varepsilon.
$$
:::

:::{#exr-limite-criterio-sucesiones}
$\star$
Dada la función $f(x)=\frac{|x|}{x}$, usar el criterio de las sucesiones para demostrar que no existe el límite de $f$ en $0$. 
:::

:::{.callout-tip collapse="true"}
## Solución
Tomando las sucesión $\left(\frac{-1}{n}\right)_{n=1}^\infty$ que converge a $0$, se tiene 

$$
\lim_{n\to\infty}f\left(\frac{-1}{n}\right)=\lim_{n\to\infty}\frac{|-1/n|}{-1/n} = -1.
$$

Y tomando la sucesión $\left(\frac{1}{n}\right)_{n=1}^\infty$ que también converge a $0$, se tiene

$$
\lim_{n\to\infty}f\left(\frac{1}{n}\right)=\lim_{n\to\infty}\frac{|1/n|}{1/n} = 1.
$$

Por tanto, por el criterio de las sucesiones convergentes, no existe el límite de $f$ en $0$.
:::

:::{#exr-limite-funcion-Dirichlet}
La función $f:\mathbb{R}\to \mathbb{R}$ dada por

$$
f(x)=\begin{cases}
1, & \mbox{si } x\in\mathbb{Q},\\ 
0, & \mbox{si } x\not\in \mathbb{Q}
\end{cases}
$$
se conoce como la _función de Dirichlet_. Demostrar que no existe el límite de $f$ en cualquier número real.
:::

:::{.callout-tip collapse="true"}
## Solución
Tomemos cualquier $a\in\mathbb{R}$ y sea $(x_n)_{n=1}^\infty$ una sucesión de números racionales que converja a $a$. Entonces la sucesión $(f(x_n))_{n=1}^\infty = (1)_{n=1}^\infty$ que converge a $1$. Por otro lado, sea $(y_n)_{n=1}^\infty$ una sucesión de números irracionales que converja a $a$. Entonces la sucesión $(f(y_n))_{n=1}^\infty = (0)_{n=1}^\infty$ que converge a $0$. Por tanto, por el criterio de la sucesiones convergentes no existe el límite de $f$ en $a$. 
:::

:::{#exr-limite-coseno}
$\star$
Demostrar que no existe $\lim_{x\to 0}\cos\left(\frac{1}{x}\right)$.
:::

:::{.callout-tip collapse="true"}
## Solución
Tomando la sucesión $\left(\frac{1}{(2n-1)\pi/2}\right)_{n=1}^\infty$ que converge a $0$, se tiene que 

$$
\lim_{n\to\infty}\cos\left(\frac{1}{\frac{1}{(2n+1)\pi/2}}\right) = \lim_{n\to\infty
}\cos((2n-1)\pi/2) = 0.
$$

Y tomando la sucesión $\left(\frac{1}{2n\pi}\right)_{n=1}^\infty$, que también converge a $0$, se tiene que 

$$
\lim_{n\to\infty}\cos\left(\frac{1}{\frac{1}{2n\pi}}\right) = \lim_{n\to\infty
}\cos(2n\pi) = 1.
$$

Por tanto, por el criterio de las sucesiones convergentes, no existe el límite de $\cos\left(\frac{1}{x}\right)$ en $0$.
:::

:::{#exr-limite-polinomios}
Dado un polinomio $p(x)$, demostrar que $\lim_{x\to a}p(x)=p(a)$ $\forall a\in\mathbb{R}$.
:::

:::{.callout-tip collapse="true"}
## Solución
Sea $p(x)=a_0+a_1x+a_2x^2+\cdots+a_nx^n$, entonces, por el álgebra de límites se tiene,

\begin{align*}
\lim_{x\to a}p(x) &= \lim_{x\to a} a_0+a_1x+a_2x^2+\cdots+a_nx^n\\ 
& = \lim_{x\to a} a_0 + \lim_{x\to a} a_1x +\lim_{x\to a} a_2x^2 + \cdots + \lim_{x\to a}a_nx^2 \\ 
&= a_0 + a_1 \lim_{x\to a} x + a_2\lim_{x\to a}x^2 + \cdots + a_n\lim_{x\to a}x^n\\ 
& = a_0+a_1a+a_2a^2+\cdots+a_na^n = p(a)
\end{align*}
:::

:::{#exr-limite-funciones-racionales}
Dada una función racional $f(x)=\frac{p(x)}{q(x)}$ $\forall x\in\mathbb{R}$ tal que $q(x)\neq 0$, demostrar que $\lim_{x\to a}f(x)=f(a)$ $\forall a\in\mathbb{R}$ tal que $q(a)\neq 0$.
:::

:::{.callout-tip collapse="true"}
## Solución
Sea $f(x)=\frac{p(x)}{q(x)}$ con $p(x)$ y $q(x)$ dos polinomios. Entonces, por el ejercicio anterior y el álgebra de límites se tiene que 

\begin{align*}
\lim_{x\to a}f(x) &= \lim_{x\to a} \frac{p(x)}{q(x)} = \frac{\lim_{x\to a} p(x)}{\lim_{x\to a}q(x)} = \frac{p(a)}{q(a)}=f(a).
\end{align*}
:::

:::{#exr-limite-emparedado}
$\star$
Demostrar, haciendo uso del [teorema de compresión de funciones](https://aprendeconalf.es/analisis-manual/limites.html#thm-compresión-funciones) que $\lim_{x\to 0}\frac{1-\cos(x)}{x} = 0$.
:::

:::{.callout-tip collapse="true"}
## Solución
\begin{align*}
\lim_{x\to 0}\frac{1-\cos(x)}{x} &= \lim_{x\to 0}\frac{(1-\cos(x))(1+\cos(x))}{x(1+\cos(x))} =  \lim_{x\to 0}\frac{1-\cos(x)^2}{x(1+\cos(x))}\\ 
&= \lim_{x\to 0}\frac{\operatorname{sen}(x)^2}{x(1+\cos(x))} = \lim_{x\to 0}\frac{\operatorname{sen}(x)}{x}\frac{\operatorname{sen}(x)}{1+\cos(x)} =\\ 
&= \lim_{x\to 0}\frac{\operatorname{sen}(x)}{x}\lim_{x\to 0}\frac{\operatorname{sen}(x)}{1+\cos(x)} =1\cdot 0 = 0.
\end{align*}
:::

:::{#exr-limites-1}
$\star$
Calcular los siguientes límites si existen:

:::: {.columns}
::: {.column}
a. $\displaystyle \lim_{x\to 2} \dfrac{x^2+x-6}{x-2}$

a. $\displaystyle \lim_{x\to 1}\dfrac{x^3-3x+2}{x^4-4x+3}$

a. $\displaystyle \lim_{x\to 0}\dfrac{\operatorname{sen}(x+a)-\operatorname{sen}(a)}{x}$

a. $\displaystyle \lim_{x\to\infty}\dfrac{x^2-3x+2}{e^{2x}}$

a. $\displaystyle \lim_{x\to\infty}\dfrac{\log(x^2-1)}{x+2}$

a. $\displaystyle \lim_{x\to 1}\dfrac{\log(1/x)}{\operatorname{tg}(x+\dfrac{\pi}{2})}$

a. $\displaystyle \lim_{x\to a}\dfrac{x^n-a^n}{x-a}\quad n\in \mathbb{N}$

a. $\displaystyle \lim_{x\to 1}\dfrac{\sqrt[n]{x}-1}{\sqrt[m]{x}-1} \quad n,m \in \mathbb{Z}$

a. $\displaystyle \lim_{x\to 0}\dfrac{\operatorname{sen}(x)-x}{x^3}$
:::

::: {.column}
j. $\displaystyle \lim_{x\to \pi/4}\dfrac{\operatorname{sen}(x)-\cos(x)}{1-\operatorname{tg}(x)}$

a. $\displaystyle \lim_{x\to 0}x^2e^{1/x^2}$

a. $\displaystyle \lim_{x\to 0}\left(1+x\right)^{1/x}$

a. $\displaystyle \lim_{x\to \infty} \sqrt[x]{x^2}$

a. $\displaystyle \lim_{x\to 0^+}\left(\dfrac{1}{x}\right)^{\operatorname{tg}(x)}$

a. $\displaystyle \lim_{x\to 0}\cos(x)^{1/\operatorname{sen}(x)}$

a. $\displaystyle \lim_{x\to 0}\dfrac{6}{4+e^{-1/x}}$

a. $\displaystyle \lim_{x\to \infty}\left(\sqrt{x^2+x+1}-\sqrt{x^2-2x-1}\right)$.

a. $\displaystyle \lim_{x\to \pi/2}\sec(x)-\operatorname{tg}(x)$
:::
:::

:::

:::{.callout-tip collapse="true"}
## Solución
a.  $\displaystyle \lim_{x\to 2} \dfrac{x^2+x-6}{x-2} =  \lim_{x\to 2} \dfrac{(x+3)(x-2)}{x-2} = \lim_{x\to 2} \frac{x+3}{1}=5$.

a. 

    \begin{align*}
    \lim_{x\to 1}\dfrac{x^3-3x+2}{x^4-4x+3} &= \lim_{x\to 1}\dfrac{(x-1)^2(x+2)}{(x-1)^2(x^2+2x+3)}\\  
    &= \lim_{x\to 1}\dfrac{(x+2)}{(x^2+2x+3)}= \frac{3}{6}=\frac{1}{2}.
    \end{align*}

a.  Aplicando la propiedad trigonométrica $\operatorname{sen}(x+a)=\operatorname{sen}(x)\cos(a)+\cos(x)\operatorname{sen}(a)$, se tiene

    \begin{align*}
    \lim_{x\to 0}\frac{\operatorname{sen}(x+a)-\operatorname{sen}(a)}{x} &= \lim_{x\to 0}\frac{\operatorname{sen}(x)\cos(a)+\cos(x)\operatorname{sen}(a)-\operatorname{sen}(a)}{x} \\ 
    &= \lim_{x\to 0}\frac{\operatorname{sen}(x)\cos(a)-\operatorname{sen}(a)(1-\cos(x))}{x} \\ 
    &= \cos(a)\lim_{x\to 0}\frac{\operatorname{sen}(x)}{x}-\operatorname{sen}(a)\lim_{x\to 0}\frac{1-\cos(x)}{x}\\
    &= \cos(a)\lim_{x\to 0}\frac{x}{x}-\operatorname{sen}(a)\lim_{x\to 0}\frac{x^2/2}{x} \tag{1}\\
    & = \cos(a)\cdot 1-\operatorname{sen}(a)\cdot 0= \cos(a).
    \end{align*}
    (1)$\operatorname{sen}(x)\approx x$ y $\cos(x)\approx x^2/2$.

a.  Como $x<e^x$ $\forall x>0$, se tiene que 

    $$
    0<\frac{x}{2}<e^{x/2} \Rightarrow 0< x < 2e^{x/2} \Rightarrow  0< \frac{x}{e^{2x}} < \frac{2e^{x/2}}{e^{2x}} = \frac{2}{e^{3x/2}},$$

    de modo que, como $\lim_{x\to\infty}\frac{2}{e^{3x/2}}=0$,  aplicando el teorema de compresión de funciones se tiene que $\lim_{x\to\infty} \frac{x}{e^{2x}}=0$.

    Usando este resultado se tiene,

    $$\lim_{x\to\infty}\dfrac{x^2-3x+2}{e^{2x}} = \lim_{x\to\infty}\dfrac{x^2}{e^{2x}}-3\lim_{x\to\infty} \frac{x}{e^{2x}} + \lim_{x\to\infty} \frac{2}{e^{2x}} = 0.
    $$

a.  Cuando $x\to\infty$, $\frac{\log(x^2-1)}{x+2}\to \frac{\infty}{\infty}$ que es indeterminado. Aplicando la regla de L'Hôpital se tiene,

    $$
    \lim_{x\to\infty}\dfrac{\log(x^2-1)}{x+2} =\lim_{x\to\infty}\frac{\frac{2x}{x^2-1}}{1} = \lim_{x\to\infty}\frac{\frac{2x}{x^2}}{\frac{x^2-1}{x^2}} = \lim_{x\to\infty}\frac{\frac{2}{x}}{1-\frac{1}{x^2}} = 0.
    $$

a.  $\displaystyle \lim_{x\to 1}\frac{\log(1/x)}{\operatorname{tg}(x+\frac{\pi}{2})} = \frac{\lim_{x\to 1}\log(1/x)}{\lim_{x\to 1}\operatorname{tg}(x+\frac{\pi}{2})} = \frac{\log(1)}{\operatorname{tg}(1+\frac{\pi}{2})}=0$

a.  $x^n-a^n = (x-a)(x^{n-1}+ax^{n-2}+a^2x^{n-3}+\cdots + a^{n-2}x+a^{n-1})$ $\forall n\in\mathbb{N}$, $n\geq 2$. Así pues, 

    \begin{align*}
    \lim_{x\to a}\dfrac{x^n-a^n}{x-a} &= \lim_{x\to a}\frac{(x-a)(x^{n-1}+ax^{n-2}+\cdots + a^{n-2}x+a^{n-1})}{x-a} \\ 
    &= \lim_{x\to a} x^{n-1}+ax^{n-2}+\cdots + a^{n-2}x+a^{n-1}\\  
    &= a^{n-1}+\stackrel{n}{\dots}+a^{n-1} = na^{n-1}
    \end{align*}

a.  Cuando $x\to 1$ $\frac{\sqrt[n]{x}-1}{\sqrt[m]{x}-1}\to \frac{0}{0}$ que es indeterminado. Usando el resultado del límite anterior se tiene

    \begin{align*}
    \lim_{x\to 1}\frac{\sqrt[n]{x}-1}{\sqrt[m]{x}-1} 
    &= \lim_{x\to 1}\frac{x^{1/n}-1}{x^{1/m}-1} 
    = \lim_{x\to 1}\frac{\frac{x^{1/n}-1}{x-1}}{\frac{x^{1/m}-1}{x-1}} \\
    &= \frac{1/n}{1/m}   
    = \frac{m}{n}.
    \end{align*}

a.  Cuando $x\to 0$ $\frac{\operatorname{sen}(x)-x}{x^3}\to \frac{0}{0}$ que es indeterminado. Aplicando la regla de L'Hôpital varias veces se tien

    \begin{align*}
    \lim_{x\to 0}\frac{\operatorname{sen}(x)-x}{x^3} 
    &= \lim_{x\to 0}\frac{\cos(x) -1}{3x^2} \tag{L'Hôpital} \\
    &= \lim_{x\to 0}\frac{-\sin(x)}{6x} \tag{L'Hôpital} \\
    &= \lim_{x\to 0}\frac{-\cos(x)}{6} \tag{L'Hôpital} \\
    &= -\frac{1}{6}.
    \end{align*}

a.  Aplicando propiedades trigonométricas se tiene

    \begin{align*}
    \lim_{x\to \pi/4}\frac{\operatorname{sen}(x)-\cos(x)}{1-\operatorname{tg}(x)} &= \lim_{x\to \pi/4}\frac{\operatorname{sen}(x)-\cos(x)}{1-\frac{\operatorname{sen}(x)}{\cos(x)}}\\ 
    & = \lim_{x\to \pi/4}\frac{\operatorname{sen}(x)-\cos(x)}{\frac{\cos(x)-\operatorname{sen}(x)}{\cos(x)}}\\ 
    & = \lim_{x\to \pi/4} -\cos(x) = \frac{-\sqrt{2}}{2}.
    \end{align*}

a.  Cuando $x\to 0$, $x^2e^{1/x^2}\to 0\cdot \infty$, que es indeterminado. Transformando la indeterminación en una de tipo cociente y aplicando la regla de L'Hôpital se tiene

    \begin{align*}
    \lim_{x\to 0}x^2e^{1/x^2} &= \lim_{x\to 0}\frac{e^{1/x^2}}{1/x^2} = \lim_{x\to 0}\frac{e^{1/x^2}\frac{-2}{x^3}}{-2/x^3} = \lim_{x\to 0} e^{1/x^2} =\infty.
    \end{align*}

a.  Cuando $x\to 0$, $\left(1+x\right)^{1/x}\to 1^\infty$, que es una indeterminación de tipo potencia. Aplicando el logaritmo y su inversa, la función exponencial, se convierte en en una indeterminación de tipo cociente.

    \begin{align*}
    \lim_{x\to 0}\left(1+x\right)^{1/x} 
    &= \lim_{x\to 0}e^{\ln(\left(1+x\right)^{1/x})}
    = e^{\lim_{x\to 0}\frac{\ln(1+x)}{x}} \tag{$\ln(1+x)\approx x$}\\  
    &= e^{\lim_{x\to 0}\frac{x}{x}} 
    = e^{\lim_{x\to 0}1} 
    = e^1 
    = e.
    \end{align*}

a.  Cuando $x\to\infty$ $\sqrt[x]{x^2}=x^{2/x}\to \infty^0$, que es indeterminado. Transformando la indeterminación en una de tipo cociente y aplicando la regla de L'Hôpital, se tiene

    \begin{align*}
    \lim_{x\to \infty} \sqrt[x]{x^2} 
    &= \lim_{x\to \infty} x^{2/x} = \lim_{x\to \infty} e^{\ln(x^{2/x})}\\
    & = e^{\lim_{x\to \infty} \frac{2\ln(x)}{x}} = e^{\lim_{x\to \infty} \frac{\frac{2}{x}}{1}} = 1.
    \end{align*}

a.  Cuando $x\to 0^+$ $\left(\dfrac{1}{x}\right)^{\operatorname{tg}(x)} \to = \infty^0$, que es una indeterminación de tipo potencia. Para convertirla en una de tipo cociente aplicamos el logaritmo y su inversa, la función exponencial.

    \begin{align*}
    \lim_{x\to 0^+}\left(\dfrac{1}{x}\right)^{\operatorname{tg}(x)}
    &= \lim_{x\to 0^+}e^{\ln\left(\left(\frac{1}{x}\right)^{\operatorname{tg}(x)}\right)}
    = e^{\lim_{x\to 0^+} \operatorname{tg}(x) \ln\left(\frac{1}{x}\right)} \\
    &= e^{\lim_{x\to 0^+} \frac{\ln\left(\frac{1}{x}\right)}{\frac{1}{\operatorname{tg}(x)}}}
    = e^{\lim_{x\to 0^+} \frac{x\frac{-1}{x^2}}{\frac{-1}{\operatorname{sen}(x)^2}}} \tag{L'Hôpital} \\
    &= e^{\lim_{x\to 0^+} \frac{\operatorname{sen}(x)^2}{x}} 
    = e^{\lim_{x\to 0^+} \operatorname{sen}(x)\frac{\operatorname{sen}(x)}{x}} \tag{$\operatorname{sen}(x)\approx x$} \\
    &= e^{\lim_{x\to 0^+} \operatorname{sen}(x)} 
    = e^0
    = 1.
    \end{align*}

a.  Cuando $x\to 0$, $\cos(x)^{1/\operatorname{sen}(x)} \to 1^\infty$, que es una indeterminación de tipo potencia. Para convertirla en una de tipo cociente aplicamos el logaritmo y su inversa, la función exponencial.

    \begin{align*}
    \lim_{x\to 0}\cos (x)^{1/\operatorname{sen}(x)} 
    &= \lim_{x\to 0}e^{\ln\left(\cos(x)^{1/\operatorname{sen}(x)}\right)}  
    =  e^{\lim_{x\to 0}1/\operatorname{sen}(x)\ln(\cos(x))} \\
    &= e^{\lim_{x\to 0}\frac{\ln(\cos(x))}{\operatorname{sen}(x)}}
    = e^{\lim_{x\to 0}\frac{\frac{1}{\cos(x)}(-\operatorname{sen}(x))}{\cos(x)}} \tag{L'Hôpital} \\
    &= e^{\lim_{x\to 0}\frac{-\operatorname{sen}(x)}{\cos(x)^2}}
    = e^0
    = 1.
    \end{align*}

a.  Como el signo del exponente de la función exponencial $1/x$ depende de si $x$ se aproxima a $0$ por la izquierda o por la derecha, en este caso estudiamos los límites laterales.

    Como $\lim_{x\to 0^-}\frac{-1}{x} = \infty$ se tiene que 

    $$
    \lim_{x\to 0^-}\frac{6}{4+e^{-1/x}} = \frac{6}{4+e^\infty} = 0.
    $$

    Y como $\lim_{x\to 0^+}\frac{-1}{x} = -\infty$ se tiene que 

    $$
    \lim_{x\to 0^-}\frac{6}{4+e^{-1/x}} = \frac{6}{4+e^{-\infty}} = \frac{6}{4}.
    $$

    Como los límites laterales son distintos, no existe el límite global.

a.  Cuando $x\to \infty$, $\sqrt{x^2+x+1}-\sqrt{x^2-2x-1} \to \infty-\infty$, que es una indeterminación de tipo diferencia. Para transformarla en una indeterminación de tipo cociente multiplicamos y dividimos por el conjugado.

    \begin{align*}
    \lim_{x\to \infty} \sqrt{x^2+x+1}-\sqrt{x^2-2x-1}
    &= \lim_{x \to \infty} \frac{(\sqrt{x^2+x+1} - \sqrt{x^2-2x-1})(\sqrt{x^2+x+1} + \sqrt{x^2-2x-1})}{\sqrt{x^2+x+1} + \sqrt{x^2-2x-1}} \\
    &= \lim_{x \to \infty} \frac{x^2+x+1 - (x^2-2x-1)}{\sqrt{x^2+x+1} + \sqrt{x^2-2x-1}} \\
    &= \lim_{x \to \infty} \frac{3x}{\sqrt{x^2+x+1} + \sqrt{x^2-2x-1}} \\
    &= \lim_{x \to \infty} \frac{3x}{x\left(\sqrt{1+\frac{1}{x}+\frac{1}{x^2}}\right) + x\left(\sqrt{1-\frac{2}{x}-\frac{1}{x^2}}\right)} \\
    &= \lim_{x \to \infty} \frac{3}{\sqrt{1+\frac{1}{x}+\frac{1}{x^2}} + \sqrt{1-\frac{2}{x}-\frac{1}{x^2}}} 
    = \frac{3}{2}.
    \end{align*}

a.  Cuando $x\to \pi/2$, $\sec(x)-\operatorname{tg}(x) \to \infty-\infty$, que es una indeterminación del tipo diferencia. Ahora bien, en este caso si escribimos la secante en función del coseno y la tangente en función de seno y el coseno, la indeterminación se transforma en otra de tipo cociente.

    \begin{align*}
    \lim_{x\to \pi/2}\sec(x)-\operatorname{tg}(x)
    &= \lim_{x\to \pi/2}\frac{1}{\cos(x)}-\frac{\operatorname{sen}(x)}{\cos(x)}
    = \lim_{x\to \pi/2}\frac{1-\operatorname{sen}(x)}{\cos(x)} \\
    &= \lim_{x\to \pi/2}\frac{-\cos(x)}{-\operatorname{sen}(x)}
    = 0. \tag{L'Hôpital}
    \end{align*}
:::

:::{#exr-ejemplos-limites-laterales}
$\star$
Dar ejemplo de funciones que cumplan las siguientes condiciones:

a. $\lim_{x\to 0}f(x)=+\infty$ y $\lim_{x\to \infty}f(x)=0$.

b. $\lim_{x\to 3^+}f(x)=+\infty$, $\lim_{x\to 3^-}f(x)=-\infty$ y $\lim_{x\to \infty}f(x)=1$.

c. $\lim_{x\to 0^+}f(x)=+\infty$ y $\lim_{x\to \infty}f(x)=-\infty$
:::

:::{.callout-tip collapse="true"}
## Solución
a. $f(x)=\frac{1}{x^2}$.

a. $g(x)=\frac{x}{x-3}$.

a. $h(x)=-\ln(x)$.
:::

:::{#exr-limite-laterales}
$\star$
Sea $g(x)=e^{1/x}$ $\forall x\neq 0$. Demostrar que no existe el límite de $g$ en $0$.
:::

:::{.callout-tip collapse="true"}
## Solución
Basta con probar que el límite lateral por la derecha no existe. Para ello, tomando la sucesión de términos positivos $\left(\frac{1}{n}\right)_1^\infty$ que converge a $0$, se tiene que

$$
\lim_{n\to\infty}g\left(\frac{1}{n}\right) = \lim_{n\to\infty}e^{\frac{1}{1/n}} =  \lim_{n\to\infty}e^n = \infty.
$$
Así pues, según el criterio de las sucesiones convergentes, no existe el límite por la derecha de $g$ en $0$, y por tanto tampoco existe el límite.
:::

:::{#exr-limites-laterales}
Dada la función 

$$
f(x)=\begin{cases}
x^2, \mbox{si } x\leq 1,\\ 
ax-1, \mbox{si } x>1
\end{cases}
$$

con $a\in\mathbb{R}$. ¿Para que valor de $a$ existe el límite de $f$ en $1$?
:::

:::{.callout-tip collapse="true"}
## Solución
Los límtes laterales en 1 valen 

$\lim_{x\to 1^-} f(x) = \lim_{x\to 1^-} x^2 = 1^2 = 1.$
$\lim_{x\to 1^+} f(x) = \lim_{x\to 1^+} ax-1 = a-1.$

Para que exista el límite de $f$ en $1$ debe ser $\lim_{x\to 1^-}f(x)=\lim_{x\to 1^+}f(x)$, es decir, $1=a-1$, luego debe ser $a=2$.
:::

:::{#exr-limites-laterales-2}
$\star$
Calcular los límites laterales de la función
$f(x)=\dfrac{1}{1+e^{\frac{1}{1-x}}}$ en el punto $x=1$. ¿Existe el límite en ese punto?
:::

:::{.callout-tip collapse="true"}
## Solución
\begin{align*}
\lim_{x\to 1^-}f(x) &= \lim_{x\to 1^-} \frac{1}{1+e^{\frac{1}{1-x}}} = \frac{1}{1+\lim_{x\to 1^-}e^\frac{1}{1-x}}\\ 
&= \frac{1}{1+e^{\lim_{x\to 1^-}\frac{1}{1-x}}} =  \frac{1}{1+e^\infty} = \frac{1}{1+\infty} = 0.
\end{align*}

\begin{align*}
\lim_{x\to 1^+}f(x) &= \lim_{x\to 1^+} \frac{1}{1+e^{\frac{1}{1-x}}} = \frac{1}{1+\lim_{x\to 1^+}e^\frac{1}{1-x}}\\ 
&= \frac{1}{1+e^{\lim_{x\to 1^+}\frac{1}{1-x}}} =  \frac{1}{1+e^{-\infty}} = \frac{1}{1+0} = 1.
\end{align*}

Como los límites laterales son distintos, no existe el límite de $f$ en $1$.
:::

:::{#exr-asintotas}
$\star$
Calcular las asíntotas de las siguientes funciones:

:::: {.columns}
::: {.column}
a. $f(x)=(1-x)e^x$

a. $g(x)=xe^{1/x}$

a. $h(x)=2x^2-\ln(x)$
:::

::: {.column}
d. $i(x)=\log(x^2+3x+2)$

a. $j(x)=\dfrac{x^3}{(x+1)^2}$

a. $k(x)=\cos x-\log(\cos x)$
:::
:::
:::

:::{.callout-tip collapse="true"}
## Solución
a. $f$ está definida en $\mathbb{R}$, así que no tiene asíntotas verticales. 

    Para ver si $f$ tiene asíntotas horizontales estudiamos los límites en el infinito. Cuando $x\to -\infty$ $(1-x)e^x\to -\infty\cdot 0$ que es indeterminado. Transformando la indeterminación en una de tipo cociente

    \begin{align*}
    \lim_{x\to -\infty}(1-x)e^x &= \lim_{x\to -\infty}\frac{1-x}{e^{-x}} = \lim_{x\to -\infty}\frac{1}{e^{-x}}- \lim_{x\to -\infty} \frac{-x}{e^{-x}}\\ 
    &= 0 -\lim_{x\to -\infty}\frac{-x}{e^{-x}}.
    \end{align*}

    Por otro lado $\forall x<0$ se cumple que $e^{-x}\geq x^2$, por lo que $0\leq \frac{-x}{e^{-x}}\leq \frac{-x}{x^2}=\frac{1}{x}$, y como $\lim_{x\to -\infty}\frac{-1}{x}=0$, por el teorema de compresión de funciones se tiene que $\lim_{x\to -\infty}\frac{-x}{e^{-x}} = 0$.

    Así pues, $y=0$ es una asíntota horizontal en $-\infty$.

    Por otro lado, $\lim_{x\to \infty}(1-x)e^x = -\infty\cdot \infty = -\infty$, de modo que no hay asíntota horizontal en $\infty$.

    Finalmente para ver si $f$ tiene asíntotas oblicuas, estudiamos estudiamos el límite de $f(x)/x$ en $\infty$ (en $-\infty$ no puede haber asíntota oblicua porque existe una horizontal).

    $$
    \lim_{x\to \infty}\frac{(1-x)e^x}{x} = \lim_{x\to \infty} \frac{1-x}{x}\lim_{x\to \infty}e^x = -1\cdot \infty = -\infty.
    $$

    Por tanto, tampoco existe asíntota oblicua en $\infty$.

a. $g$ está definida en $\mathbb{R}\setminus \{0\}$, así que, el único punto donde pueden existir asíntotas verticales es $x=0$. Calculando los límites laterales se tiene

    \begin{align*}
    \lim_{x\to 0^-} xe^{1/x} &= \lim_{x\to 0^-}x \lim_{x\to 0^-}e^{1/x} = 0\cdot e^{-\infty} = 0\cdot 0 = 0.\\ 
    \lim_{x\to 0^+} xe^{1/x} &= \lim_{x\to 0^+}\frac{e^{1/x}}{1/x} = \lim_{x\to 0^+}\frac{(e^{1/x})'}{(1/x)'} \tag{\small L'Hôpital}\\ 
    &= \lim_{x\to 0^+}\frac{e^{1/x}(1/x)'}{(1/x)'} = \lim_{x\to 0^+}e^{1/x} = \infty. 
    \end{align*}
    
    Por tanto, $g$ tiene asíntota vertical $x=0$ por la derecha, pero no por la izquierda.

    Para ver si $g$ tiene asíntotas horizontales estudiamos los límites en el infinito. 

    \begin{align*}
    \lim_{x\to -\infty}xe^{1/x} &= \lim_{x\to -\infty}x \lim_{x\to -\infty}e^{1/x} = \infty \cdot 1 = \infty.\\ 
    \lim_{x\to \infty}xe^{1/x} &= \lim_{x\to \infty}x \lim_{x\to \infty}e^{1/x} = \infty \cdot 1 = \infty.
    \end{align*}

    Así pues, ambos límites no existen y, por tanto, $g$ no tiene asíntotas horizontales.

    Finalmente para ver si $f$ tiene asíntotas oblicuas, estudiamos estudiamos el límite de $f(x)/x$ en $\pm\infty$.

    $$
    \lim_{x\to -\infty}\frac{xe^{1/x}}{x} = \lim_{x\to -\infty} e^{1/x} = e^0 =1.
    $$

    Luego, existe una asíntota oblicua en $-\infty$ con pendiente $1$. Para ver el término independiente de la asíntota calculamos el límite de $f(x)-1\cdot x$ en $-\infty$.

    \begin{align*}
    \lim_{x\to -\infty}xe^{1/x}-x &= \lim_{x\to -\infty} x(e^{1/x}-1) = \lim_{x\to -\infty} \frac{e^{1/x}-1}{1/x} \\ 
    &= \lim_{x\to -\infty} \frac{(e^{1/x}-1)'}{(1/x)'} \tag{\small L'Hôpital}\\ 
    &= \lim_{x\to -\infty} \frac{e^{1/x} (1/x)'}{(1/x)'} = \lim_{x\to -\infty} e^{1/x} = 1.
    \end{align*}
  
    Así pues, $g$ tiene una asíntota oblicua $y=x+1$ en $-\infty$. Del mismo modo se puede probar que esta misma recta es asíntota oblicua en $\infty$.

a. $h(x)$ está definida en $\mathbb{R}^+$, así que, el único punto donde pueden existir asíntotas verticales $x=0$. Como $h$ no está definida para $x<0$, estudiaremos el límite por la derecha en $0$.

    $$
    \lim_{x\to 0^+} 2x^2-\ln(x) = 0-\ln(0) = \infty
    $$
    Por tanto, $h$ tiene una asíntota vertical $x=0$ por la derecha, pero no por la izquierda.

    Para ver si $g$ tiene asíntotas horizontales estudiamos el límite en el infinito (en $-\infty$ no puede haber asíntota horizontal al no estar definida la función para $x<0$).

    \begin{align*}
    \lim_{x\to\infty} 2x^2-\ln(x) &= \lim_{x\to\infty}\ln(e^{2x^2-\ln(x)}) = \lim_{x\to \infty} \ln\left(\frac{e^{2x^2}}{e^{\ln(x)}}\right)\\ 
    &= \ln\left(\lim_{x\to \infty} \frac{e^{2x^2}}{x}\right) = \ln\left(\lim_{x\to \infty} \frac{(e^{2x^2})'}{x'}\right) \tag{L'Hôpital} \\ 
    &= \ln\left(\lim_{x\to \infty} \frac{e^{2x^2}4x}{1}\right) = \ln(\infty) = \infty.
    \end{align*}

    Por tanto, $h$ no tiene asíntotas horizontales. 

    Finalmente, veamos si existe asíntota oblicua en $\infty$.

    \begin{align*}
    \lim_{x\to\infty} \frac{2x^2-\ln(x)}{x} &= \lim_{x\to \infty} 2x - \frac{\ln(x)}{x}\\ 
    & = \lim_{x\to \infty} 2x -\lim_{x\to \infty}\frac{\ln(x)}{x}\\ 
    &= \lim_{x\to \infty} 2x -\lim_{x\to \infty}\frac{(\ln(x))'}{x'} \tag{L'Hôpital}\\ 
    & = \lim_{x\to \infty} 2x -\lim_{x\to \infty}\frac{1}{x}= \infty-0=\infty.  
    \end{align*}

    Luego, $h$ tampoco tiene asíntota oblicua en $\infty$.
:::

:::{#exr-acuifero}
$\star$
Mediante simulación por ordenador se ha podido cuantificar la cantidad de agua almacenada en un
acuífero en función del tiempo, $m(t)$, en millones de metros cúbicos, y el tiempo $t$ en años transcurridos
desde el instante en el que se ha hecho la simulación, teniendo en cuenta que la ecuación sólo tiene
sentido para $t>0$:

$$
m(t) = 10 + \frac{\sqrt{t}}{e^t}
$$

¿Qué cantidad de agua almacenada habrá en el acuífero asintóticamente?
:::

:::{.callout-tip collapse="true"}
## Solución
Cuando $t\to\infty $\frac{\sqrt{t}}{e^t}\to \frac{\infty}{\infty}$ que es indeterminado. Aplicando la regla de L'Hôpital se tiene

$$
\lim_{t\to \infty} 10 + \frac{\sqrt{t}}{e^t} = 10 + \lim_{t\to \infty} \frac{\sqrt{t}}{e^t} = \lim_{t\to \infty}\frac{1}{2\sqrt(t)e^t} = 10.
$$

Por tanto el volumen del lato tiende asintóticamente a 10 millones de metros cúbicos.
:::

:::{#exr-cosecha}
$\star$
La cosecha de trigo de una plantación (en toneladas) depende de la cantidad de abono $x$ según la función $f(x)=T(1-\frac{1}{2}e^{-kx})$, donde $T$ es la extensión del terreno (en hectáreas) y $k$ es la proporción de humedad. ¿Para qué cantidad de abono se conseguiría una cosecha de $T$ toneladas de trigo? 
:::

:::{.callout-tip collapse="true"}
## Solución
Como $k>0$ se tiene $\frac{1}{2}e^{-kx} = \frac{1}{2e^{kx}} < 1$ $\forall x>0$, de manera que $f(x)<T$ $\forall x>0$. Si calculamos ahora el límite en infinito se tiene

$$\lim_{x\to \infty} T(1-\frac{1}{2}e^{-kx}) = T(1-\lim_{x\to \infty}\frac{1}{2e^{kx}}) = T(1-0) = T.
$$ 

De modo la cantidad de trigo cosechada tiene asintóticamente a $T$, pero al ser menor que $T$, nunca llegará a valer $T$.
:::

:::{#exr-limites-funciones-acotadas}
Sea $f:(a,b)\to \mathbb{R}$ una función creciente. Demostrar lo siguiente:

a. Si $f$ está acotada superiormente, entonces existe $\lim_{x\to b^-}f(x)$.
b. Si $f$ no está acotada superiormente, entonces $\lim_{x\to b^-}f(x)=\infty$.
:::

:::{.callout-tip collapse="true"}
## Solución
a.  Supongamos que $f$ está acotada, entonces, por el axioma de completitud de los números reales existe el supremo $c$ de las imágenes de $(a,b)$ mediante $f$. Veamos que $\lim_{x\to b^-} f(x) = c$. 
:::

:::{#exr-continuidad-coseno}
Demostrar que la función $f(x)=\cos(x)$ es continua en todo $\mathbb{R}$.
:::

:::{.callout-tip collapse="true"}
## Solución
Sea $a\in\mathbb{R}$. Usando propiedades trigonométricas se tiene

\begin{align*}
|\cos(x)-\cos(a)|
&=|-2\operatorname{sen}\left(\frac{x+a}{2}\right)\operatorname{sen}\left(\frac{x-a}{2}\right)| \\
&= 2|\operatorname{sen}\left(\frac{x+a}{2}\right)||\operatorname{sen}\left(\frac{x-a}{2}\right)| \\
&\leq 2\frac{|x-a|}{2}=|x-a|,
\end{align*}

ya que $\operatorname{sen}(x)\leq x$ $\forall x\in\mathbb{R}^+$ y $\operatorname{sen}(x)\leq 1$ $\forall x\in\mathbb{R}$.

Así pues, para cualquier $\varepsilon>0$ existe $\delta=\varepsilon>0$ tal que si $|x-a|<\delta=\varepsilon$, entonces $|\cos(x)-\cos(a)|<|x-a|=\varepsilon$,
y por tanto, $\lim_{x\to a}\cos(x) = \cos(a)$, lo que demuestra que la función coseno es continua en todo su dominio.
:::

:::{#exr-discontinuidad-evitable}
$\star$
¿Qué tipo de discontinuidad presenta la función $f(x)=x\cos\left(\frac{1}{x}\right)$ en $x=0$? Redefinir la función para que sea continua en dicho punto.
:::

:::{.callout-tip collapse="true"}
## Solución
La función no está definida en $x=0$ por lo que es discontinua en este punto. Para ver el tipo de discontinuidad estudiamos los límites laterales en el punto. Como $-1\leq \cos\left(\frac{1}{x}\right)\leq 1$ $\forall x\neq 0$, podemos encajar $f$ entre las siguientes funciones 

$$
-x \leq x\cos\left(\frac{1}{x}\right) \leq x,
$$

y como $\lim_{x\to 0^-} -x = \lim_{x\to 0^-} x=0$, por el teorema de compresión de límites se tiene que $\lim_{x\to 0^-} f(x) =0$. Y del mismo modo, como $\lim_{x\to 0^+} -x = \lim_{x\to 0^+} x=0$, por lo que $\lim_{x\to 0^+} f(x) =0$.

Así pues, el límite existe y la discontinuidad es de tipo evitable. Para conseguir que la función sea continua en $x=0$ basta con definir la función en este punto como el valor de su límite, es decir, 

$$
f(x) =
\begin{cases}
x\cos\left(\frac{1}{x}\right) & \mbox{si $x\neq 0$,}\\
0 & \mbox{si $x=0$.}
\end{cases}
$$
:::

:::{#exr-clasificacion-dicontinuidades}
$\star$
Estudiar la continuidad de las siguientes funciones en los puntos que se indican:

a. $f(x)=\dfrac{e^x-1}{e^x+1}$, en el punto $x=0$.

a. 
$$
g(x)=
\begin{cases}
\frac{1+e^{1/x}}{1-e^{1/x}} & \mbox{si $x\neq 0$,} \\
1 &  \mbox{si $x=0$,}
\end{cases}
$$
en el punto $x=0$.

a. 
$$
h(x)=
\begin{cases}
x\operatorname{sen}\left(\frac{\pi}{x}\right) & \mbox{si $x\neq 0$,} \\
0 & \mbox{si $x=0$,}
\end{cases}
$$
en el punto $x=0$.

a. 
$$
i(x)=
\begin{cases}
\dfrac{1}{2^{1/x}} &  \mbox{si $x\neq 0$,} \\
0 & \mbox{si $x=0$,}
\end{cases}
$$
en el punto $x=0$.
:::

:::{.callout-tip collapse="true"}
## Solución
a.  La función no está definida en $x=0$ que para este valor se anula el denominador, por lo que la función es discontinua enb ese punto. Para ver qué tipo de discontinuidad presenta en el punto estudiamos los límites laterales de $f$ en $x=0$.

    \begin{align*}
    \lim_{x\to 0^-} \frac{e^x-1}{e^x+1}
    &= \frac{1-1}{1+1} = 0, \\
    \lim_{x\to 0^+} \frac{e^x-1}{e^x+1}
    &= \frac{1-1}{1+1} = 0.
    \end{align*}

    Por tanto, $f$ tiene una discontinuidad evitable en $x=0$.

a.  Estudiamos los límites laterales de $g$ en $x=0$.

    \begin{align*}
    \lim_{x\to 0^-} \frac{1+e^{1/x}}{1-e^{1/x}} 
    &= \frac{1+e^{-\infty}}{1-e^{-\infty}}
    = \frac{1}{1} = 1, \\
    \lim_{x\to 0^+} \frac{1+e^{1/x}}{1-e^{1/x}} 
    &= \lim_{x\to 0^+} \frac{e^{1/x}\frac{-1}{x^2}}{-e^{1/x}\frac{-1}{x^2}} \tag{L'Hôpital} \\
    &= \frac{-1}{1} = -1.
    \end{align*}

    Como ambos límites existen pero son distintos, $g$ tiene una discontinuidad de salto finito en $x=0$.

a.  Como $-1\leq \operatorname{sen}\left(\frac{\pi}{x}\right)\leq 1$  $\forall x\neq 0$, podemos encajar $h$ entre las siguientes funciones

    $$
    -x \leq x\operatorname{sen}\left(\frac{\pi}{x}\right) \leq x,
    $$

    y como $\lim_{x\to 0} -x = \lim_{x\to 0} x = 0$, se tiene que $\lim_{x\to 0} h(x) = 0 = h(0)$, por lo que la función es continua en $x=0$.    

a.  Estudiamos los límites laterales de $i$ en $x=0$.

    \begin{align*}
    \lim_{x\to 0^-} \frac{1}{2^{1/x}}
    &= \frac{1}{2^{-\infty}} 
    = \infty, \\
    \lim_{x\to 0^+} \frac{1}{2^{1/x}}
    &= \frac{1}{2^{\infty}} 
    = 0.
    \end{align*}

    Como $\lim_{x\to 0^-} i(x)=\infty$, $i$ tiene una discontinuidad de salto infinito en $x=0$.
:::

:::{#exr-clasificacion-dicontinuidades-2}
Clasificar las discontinuidades de las siguientes funciones

a. 
$$
f(x)=\frac{\frac{1}{x}-\frac{1}{x+1}}{\frac{3}{x-1}-\frac{1}{x}}.
$$

b.
$$
g(x)=
\begin{cases}
\dfrac{\operatorname{sen}(x)}{x} & \text{si $x<0$,} \\ 
e^{\frac{1}{x-1}} & \text{si $x\geq 0$.}
\end{cases}
$$
:::

:::{.callout-tip collapse="true"}
## Solución
a. A simple vista, podemos ver que se trata de una función racional y estará definida en todo $\mathbb{R}$ salvo en los puntos que anulen alguno de los denominadores. Dichos puntos son fáciles de obtener igualando a 0 los denominadores:

    \begin{align*}
    x &= 0 \\
    x+1 &= 0\Leftrightarrow x=-1 \\
    x-1 &= 0\Leftrightarrow x=1 \\
    \frac{3}{x-1}-\frac{1}{x} &= 0 \Leftrightarrow x=-\frac{1}{2}
    \end{align*}

    Por tanto, obtenemos 4 punto de discontinuidad, que son: $x=0,$ $x=1$, $x=-1$ y $x=-\frac{1}{2}$.

    Para clasificar estas cuatro discontinuidades, tenemos que estudiar los correspondientes límites por la izquierda y por la derecha.

    - Discontinuidad en $x=0$:

    \begin{align*}
    \lim_{x\rightarrow 0^{-}}f(x) &= \lim_{x\rightarrow 0^{-}}\frac{\frac{1}{x}-\frac{1}{x+1}}{\frac{3}{x-1}-\frac{1}{x}} = \lim_{x\rightarrow 0^{-}}\frac{x-1}{\left( x+1\right) \left( 2x+1\right) } = \lim_{x\rightarrow 0^{-}}\frac{-1}{1}=-1, \\
    \lim_{x\rightarrow 0^{+}}f(x) &= \lim_{x\rightarrow 0^{+}}\frac{\frac{1}{x}-\frac{1}{x+1}}{\frac{3}{x-1}-\frac{1}{x}} = \lim_{x\rightarrow 0^{+}}\frac{x-1}{\left( x+1\right) \left( 2x+1\right) } = \lim_{x\rightarrow 0^{+}}\frac{-1}{1}=-1.
    \end{align*}

    Como ambos límites coinciden, se trata de una discontinuidad evitable.

    - Discontinuidad en $x=1$:

    \begin{align*}
    \lim_{x\rightarrow 1^{-}}f(x) &= \lim_{x\rightarrow 1^{-}}\frac{\frac{1}{x}-\frac{1}{x+1}}{\frac{3}{x-1}-\frac{1}{x}} = \lim_{x\rightarrow 1^{-}}\frac{x-1}{\left( x+1\right) \left( 2x+1\right) } = \lim_{x\rightarrow 1^{-}}\frac{0}{6}=0, \\
    \lim_{x\rightarrow 1^{+}}f(x) &= \lim_{x\rightarrow 1^{+}}\frac{\frac{1}{x}-\frac{1}{x+1}}{\frac{3}{x-1}-\frac{1}{x}} = \lim_{x\rightarrow 1^{+}}\frac{x-1}{\left( x+1\right) \left( 2x+1\right) } = \lim_{x\rightarrow 1^{+}}\frac{0}{6}=0.
    \end{align*}

    De nuevo, como ambos límites coinciden, se trata de una discontinuidad evitable.

    - Discontinuidad en $x=-1$:

    \begin{align*}
    \lim_{x\rightarrow -1^{-}}f(x) &= \lim_{x\rightarrow -1^{-}}\frac{\frac{1}{x}-\frac{1}{x+1}}{\frac{3}{x-1}-\frac{1}{x}} = \lim_{x\rightarrow -1^{-}}\frac{x-1}{\left( x+1\right) \left( 2x+1\right) } = \lim_{x\rightarrow -1^{-}}\frac{-2}{-0\cdot -1}=-\infty, \\
    \lim_{x\rightarrow -1^{+}}f(x) &= \lim_{x\rightarrow -1^{+}}\frac{\frac{1}{x}-\frac{1}{x+1}}{\frac{3}{x-1}-\frac{1}{x}} = \lim_{x\rightarrow -1^{+}}\frac{x-1}{\left( x+1\right) \left( 2x+1\right) } = \lim_{x\rightarrow -1^{+}}\frac{-2}{+0\cdot -1}=\infty.
    \end{align*}

    Como ambos límites divergen, se trata de una discontinuidad de primera especie de salto infinito.

    - Discontinuidad en $x=-\frac{1}{2}$:

    \begin{align*}
    \lim_{x\rightarrow -1/2^{-}}f(x) &= \lim_{x\rightarrow -1/2^{-}}\frac{\frac{1}{x}-\frac{1}{x+1}}{\frac{3}{x-1}-\frac{1}{x}} = \lim_{x\rightarrow -1/2^{-}}\frac{x-1}{\left( x+1\right) \left( 2x+1\right) } = \lim_{x\rightarrow-1/2^{-}}\frac{-3/2}{1/2\cdot -0} = +\infty, \\
    \lim_{x\rightarrow -1/2^{+}}f(x) &= \lim_{x\rightarrow -1/2^{+}}\frac{\frac{1}{x}-\frac{1}{x+1}}{\frac{3}{x-1}-\frac{1}{x}} = \lim_{x\rightarrow -1/2^{+}}\frac{x-1}{\left( x+1\right) \left( 2x+1\right) } = \lim_{x\rightarrow-1/2^{+}}\frac{-2}{1/2\cdot +0} = -\infty.
    \end{align*}

    Por último, como ambos límites divergen, se trata también de una discontinuidad de primera especie de salto infinito.

b. La función $\frac{\operatorname{sen}(x)}{x}$ es continua en $\mathbb{R}\setminus{\{0\}}$ y en consecuencia es continua en la región donde está definida, es decir $(-\infty ,0)$. Por su parte, la función $e^{\frac 1{x-1}}$ es continua en todos los puntos en que sea continuo el exponente $\frac{1}{x-1},$ es decir en $\mathbb{R}\setminus\{1\}$, en consecuencia, es continua en toda la región en donde está definida, menos en el 1. Así pues, reduciremos el estudio de la continuidad a dos puntos, el 0 por ser donde cambia la definición de la función y el 1, por no estar definida la función $e^{\frac{1}{x-1}}.$

    Estudiamos primero la continuidad en el punto $x=0$:

    \begin{align*}
    \lim_{x\rightarrow 0^{-}}f(x) &= \lim_{x\rightarrow 0^{-}}\frac{\operatorname{sen}(x)}{x}\stackrel{\text{L}^{\prime }\text{H\^{o}pital}}{=} \lim_{x\rightarrow 0^{-}}\frac{\cos x}{1} = 1,\\
    \lim_{x\rightarrow 0^{+}}f(x) &= \lim_{x\rightarrow 0^{+}}e^{\frac{1}{x-1}} = e^{-1}.\\
    \end{align*}

    Como ambos límites laterales son distintos, en $x=0$ hay una discontinuidad de salto.

    Estudiamos ahora la continuidad en el punto $x=1$:

    \begin{align*}
    \lim_{x\rightarrow 1^{-}}f(x) &= \lim_{x\rightarrow 1^{-}}e^{\frac{1}{x-1}}=e^{-\infty }=0, \\
    \lim_{x\rightarrow 1^{+}}f(x) &= \lim_{x\rightarrow 1^{+}}e^{\frac{1}{x-1}}=e^\infty = \infty.\\ 
    \end{align*}

    Como el límite lateral por la derecha no existe, en $x=1$ hay una discontinuidad de salto infinito.
:::

:::{#exr-bolzano}
$\star$
Calcular una raíz de la función $f(x)=x^5-x+1$ con una aproximación de 2 decimales. 
:::

:::{.callout-tip collapse="true"}
## Solución
Como la función $f$ es un polinomio, que es continua en todo $\mathbb{R}$, utilizaremos el [teorema de Bolzano](https://aprendeconalf.es/analisis-manual/06-limites.html#thm-bolzano) para aproximar la raíz. Para ello, basta con encontrar un intervalo $[a,b]$ en el que $f(a)$ tenga signo distinto que $f(b)$. Podemos tomar el intervalo $[-2,-1]$ ya que $f(-2)=-29$ y $f(-1)=1$. 

Si tomamos el centro del intervalo, $f\left(\frac{(-2)+(-1)}{2}\right)=f(-1.5)= -5.0937<0$, por lo que podemos repetir el procedimiento para el intervalo $[-1.5,-1]$. 

Tomamos ahora centro del intervalo, $f\left(\frac{(-1.5)+(-1)}{2}\right)=f(-1.25)= -0.8018<0$, por lo que podemos repetir el procedimiento para el intervalo $[-1.25,-1]$. 

Tomamos de nuevo centro del intervalo, $f\left(\frac{(-1.25)+(-1)}{2}\right)=f(-1.125)= 0.323>0$, por lo que podemos repetir el procedimiento para el intervalo $[-1.25,-1.125]$.

Tomamos otra vez el centro del intervalo, $f\left(\frac{(-1.25)+(-1.125)}{2}\right)=f(-1.1875)= -0.1739<0$, por lo que podemos repetir el procedimiento para el intervalo $[-1.1875,-1.125]$. 

Tomamos una vez más el centro del intervalo, $f\left(\frac{(-1.1875)+(-1.125)}{2}\right)=f(-1.15625)= 0.0897>0$, por lo que podemos repetir el procedimiento para el intervalo $[-1.1875,-1.15625]$.

Tomamos de nuevo el centro del intervalo, $f\left(\frac{(-1.1875)+(-1.15625)}{2}\right)=f(-1.171815)= -0.0382<0$, por lo que podemos repetir el procedimiento para el intervalo $[-1.171875,-1.15625]$.

Tomamos otra vez centro del intervalo, $f\left(\frac{(-1.171875)+(-1.15625)}{2}\right)=f(-1.1640625)= 0.02668>0$, por lo que podemos repetir el procedimiento para el intervalo $[-1.171875,-1.1640625]$.

Tomamos una última vez centro del intervalo, $f\left(\frac{(-1.171875)+(-1.1640625)}{2}\right)=f(-1.16796875)= -0.0055<0$, por lo que la raíz está en el intervalo $[-1.16796875,-1.1640625]$, por lo que podemos concluir que la raíz será aproximadamente $-1.16$.
:::

:::{#exr-valor-intermedio}
Dadas dos funciones $f,g:[a,b]\to\mathbb{R}$ continuas en $[a,b]$ con $f(a)<g(a)$ y $f(b)>g(b)$, demostrar que existe $c\in(a,b)$ tal que $f(c)=g(c)$.
:::

:::{.callout-tip collapse="true"}
## Solución
Tomemos la función $h(x)=f(x)-g(x)$. Como $f$ y $g$ son continuas en $[a,b]$, $h$ también lo es. Además, se cumple que $h(a)=f(a)-g(a)<0$ y $h(b)=f(b)-g(b)>0$, por lo que podemos aplicar el [teorema de Bolzano](https://aprendeconalf.es/analisis-manual/06-limites.html#thm-bolzano) a $h$ y se tiene que existe $c\in(a,b)$ tal que $h(c)=f(c)-g(c)=0$, de donde se deduce que $f(c)=g(c)$.
:::

:::{#exr-valor-intermedio-2}
$\star$
Demostrar que las siguientes ecuaciones tienen al menos una solución real.

a. $\cos(x)=x$.
b. $e^x = -x$.
:::

:::{.callout-tip collapse="true"}
## Solución
a.  Si tomamos la función $f(x)=\cos(x)-x$, se trata de encontrar al menos una raíz de la función. Como se trata de una función continua en todo $\mathbb{R}$, basta con aplicar el [teorema de Bolzano](https://aprendeconalf.es/analisis-manual/06-limites.html#thm-bolzano) en un intervalo $[a,b]$ que cumpla que $f(a)$ tiene distinto signo que $f(b)$. Como $f(0)=\cos(0)-0=1>0$ y $f(\pi/2)=\cos(\pi/2)-\pi/2 = -\pi/2<0$, $f$ tiene al menos una raíz en el intervalo $[0,\pi/2]$ y la ecuación tiene solución en ese intervalo.

a.  Si tomamos la función $g(x)=e^x+x$, se trata de nuevo de encontrar al menos una raíz de la función. Al igual que antes, como se trata de una función continua en todo $\mathbb{R}$, basta con aplicar el [teorema de Bolzano](https://aprendeconalf.es/analisis-manual/06-limites.html#thm-bolzano) en un intervalo $[a,b]$ que cumpla que $f(a)$ tiene distinto signo que $f(b)$. Como $g(-1)=e^{-1}(-1)<0$ y $g(0)=e^0+0=1>0$, $g$ tiene al menos una raíz en el intervalo $[-e^{-1},0]$ y la ecuación tiene solución en ese intervalo.
:::