---
title: Series de números reales
lang: es
---

:::{#exr-conversion-sucesiones-series}
Demostrar que cualquier sucesión puede expresarse como una serie.
:::

:::{.callout-tip collapse="true"}
## Solución
Dada una sucesión $(a_n)_{n=1}^\infty$, veamos cómo podemos expresarla como una serie. Para ello, basta con construir la sucesión de las diferencias de dos términos consecutivos, es decir, la sucesión $(d_n)_{n=1}^\infty$ dada por:
\begin{align*}
d_1&=a_1\\ 
d_2&=a_2-a_1\\ 
d_3&=a_3-a_2\\ 
\vdots\\ 
d_{n+1}&=a_{n+1}-a_n
\end{align*}

Resulta sencillo comprobar que $a_n=\sum_{i=1}^n d_i$, por lo que la sucesión $(a_n)_{n=1}^\infty = \left(\sum_{i=1}^n d_i\right)_{n=1}^\infty = \sum d_n$.
:::  

:::{#exr-números-decimales-series}
Demostrar que la serie $\sum \frac{9}{10^n}$ converge y calcular su límite.
:::

:::{.callout-tip collapse="true"}
## Solución
Los primeros términos de la serie son 

\begin{align*}
\sum_{i=1}^1 \frac{9}{10^i} &= \frac{9}{10} = 0.9\\ 
\sum_{i=1}^2 \frac{9}{10^i} &= \frac{9}{10} + \frac{9}{100} = 0.99\\ 
\sum_{i=1}^3 \frac{9}{10^i} &= \frac{9}{10} + \frac{9}{100} + \frac{9}{1000} = 0.999\\ 
\vdots
\end{align*}

por lo que las sumas parciales cada vez están más cerca de $1$ y se puede probar fácilmente que $\sum_{n=1}^\infty \frac{9}{10^n} = \lim_{n\to\infty} \sum_{i=1}^n \frac{9}{10^i} = 1$. Para ello, dado un $\varepsilon>0$, por la propiedad arquimediana se puede tomar $k\in\mathbb{N}$ con $\frac{1}{k}<\varepsilon$, de manera que $|\sum_{i=1}^n \frac{9}{10^i} -1|<\frac{1}{10^k}<\frac{1}{k}<\varepsilon$ $\forall n\geq k$.
::: 

:::{#exr-sumas-parciales}
Si $\sum_{i=1}^n a_n=\frac{n-1}{n+1}$, ¿cuál es el término general de la sucesión $a_n$? Calcular $\sum_{n=1}^\infty a_n$.
:::

:::{.callout-tip collapse="true"}
## Solución
Sea $A_n=\sum_{i=1}^n a_i$ la suma parcial de los $n$ primeros términos de la sucesión $(a_n)_{n=1}^\infty$. Entones, el primer término de la sucesión es $a_1 = A_1= \sum_{i=1}^1 a_i = \frac{1-1}{1+1} = 0$.

Por otro lado, $A_n=A_{n-1}+a_n$ por lo que $a_n=A_n-A_{n-1} = \frac{n-1}{n+1}-\frac{n-2}{n} = \frac{2}{n(n+1)}$.

Por último, $\sum_{n=1}^\infty a_n = \lim_{n\to\infty} A_n = \lim_{n\to\infty} \frac{n-1}{n+1} = 1$.
::: 

:::{#exr-series-geometricas}
Demostrar que una serie geométrica $\sum ar^n$ converge si y solo si $|x|<1$.
:::

:::{.callout-note collapse="true"}
## Pista
Utilizar la igualdad $(1+r+r^2+\cdots + r^n)(1-r) = 1-r^{n+1}$.
:::

:::{.callout-tip collapse="true"}
## Solución
Usando la igualdad $(1+r+r^2+\cdots + r^n)(1-r) = 1-r^{n+1}$ se tiene

$$
\sum_{i=0}^n ar^i = a\frac{1-r^{n+1}}{1-r} = a\left(\frac{1}{1-r}-\frac{r^{n+1}}{1-r}\right).
$$

Si $|r|<1$ entonces $\lim_{n\to\infty}\frac{r^{n+1}}{1-r} = 0$, de manera que 

$$
\sum_{n=0}^\infty ar^n = \lim_{n\to \infty}\sum_{i=0}^n ar^i = \frac{a}{1-x}.
$$

Si $|r|>1$, entonces $\lim_{n\to\infty}\frac{r^{n+1}}{1-r}=\infty$, y la serie no converge.

Si $r=1$ entonces $\sum_{i=0}^n 1^i = n+1$ que tampoco converge, y si $r=-1$, se obtiene una sucesión de sumas alternada, ya que $\sum_{i=0}^{2n} (-1)^i = 1$ y $\sum_{i=0}^{2n+1} (-1)^i = 0$, por lo que la serie tampoco converge.
:::

:::{#exr-serie-geometrica-farmaco}
Un enfermo crónico toma cada día una pastilla con 200 mg de un principio activo. Su cuerpo es capaz de metabolizar diariamente el 90\% de la cantidad de principio activo presente. ¿Qué cantidad de principio activo quedará en el cuerpo del enfermo tras $n$ días tomando la pastilla? ¿Qué cantidad de principio activo quedará en el cuerpo del enfermo a largo plazo?
:::

:::{.callout-tip collapse="true"}
## Solución
Sea $A_n$ la cantidad de medicamento que queda en el cuerpo del enfermo tras $n$ días tomando la pastilla. Veamos cuáles son las cantidades de principio activo que quedan en el cuerpo del enfermo los primeros días.

\begin{align*}
A_1 &= 0.1\cdot 200 \mbox{ mg}\\ 
A_2 &= 0.1 (200 + 0.1\cdot 200) = 0.1\cdot 200 + 0.1^2 \cdot 200 = A_1 + 0.1^2\cdot 200 \mbox{ mg}\\ 
A_3 &= 0.1 (200 + 0.1\cdot 200 + 0.1^2 \cdot 200) = 0.1\cdot 200 + 0.1^2 \cdot 200 + 0.1^3\cdot 200 = A_2 + 0.1^3\cdot 200 \mbox{ mg}\\ 
\vdots\\
A_n &= A_{n-1} + 0.1^n \cdot 200 \mbox{ mg}
\end{align*}

Por tanto, el término general de la sucesión que subyace a la serie es $a_n = A_n-A_{n-1} = 200\cdot 0.1^n$, de manera que se trata de la serie geométrica $\sum 200\cdot 0.1^n$, y, por el ejercicio anterior, como $0.1<1$, la serie converge a $\sum_{n=1}^\infty 200\cdot 0.1^n = 200\sum_{n=1}^\infty 0.1^n = 200\frac{1}{1-0.1} = 222.2222\cdots$ mg.
:::

:::{#exr-propensiones-marginales-gasto-ahorro}
Cuando una persona gasta una cantidad de dinero en un bien o servicio, la persona que recibe el dinero directa o indirectamente, también gasta un porcentaje $k$ de esa cantidad en otros bienes y servicios, mientras que ahorra el resto. En Economía, el valor $\frac{k}{100}$ se conoce como _propensión marginal al consumo_ mientras que $1-\frac{k}{100}$ se conoce como _propensión marginal al ahorro_. Si una persona inicia el proceso gastando una cantidad $x$, qué cantidad total se habrá gastado después de $n$ transacciones? ¿Hacia dónde converge el gasto cuando se realiza un número infinito de transacciones? ¿A largo plazo, cuál es el efecto multiplicador sobre el gasto inicial de una propensión marginal al consumo de $0.6$?
:::

:::{.callout-tip collapse="true"}
## Solución
Sea $a_n$ el dinero total gastado en la transacción $n$. Veamos el total de dinero gastado en las primeras $n$ transacciones.

\begin{align*}
a_0 &=  x\\
a_1 &= x\frac{k}{100}\\
a_2 &= x\left(\frac{k}{100}\right)^2\\
\vdots\\
a_n &= x\left(\frac{k}{100}\right)^n
\end{align*}

Por tanto, el dinero total gastado tras $n$ transacciones será $\sum_{i=0}^n x\left(\frac{k}{100}\right)^i$, y como se trata de una serie geométrica, tal y como se ha visto en el @exr-series-geometricas, la suma vale

$$
\sum_{i=0}^n x\left(\frac{k}{100}\right)^i = x\frac{1-\left(\frac{k}{100}\right)^{n+1}}{1-\frac{k}{100}}.
$$

Como la razón es $\frac{k}{100}<1$, la serie converge y 
$$
\sum_{n=0}^\infty x\left(\frac{k}{100}\right)^n = \frac{x}{1-\frac{k}{100}},
$$

es decir, la cantidad inicial dividida por la propensión marginal al ahorro.

Para una propensión marginal al consumo de $0.6$ se tiene $\sum_{n=0}^\infty x\left(0.6\right)^n = \frac{x}{1-0.6} = 2.5x$, así que se produce un efecto multiplicador del $2.5$.
:::

:::{#exr-cuenta-ahorro}
Una cuenta de ahorro ofrece un $5$% de interés anual. Una persona abre la cuenta de ahorro con un depósito de $2000$€ y cada año que pasa hace un depósito de $1000$€. Calcular la cantidad de dinero que habrá en la cuenta después de $n$ años de forma cerrada. ¿Converge la serie asociada? 
:::

:::{.callout-tip collapse="true"}
## Solución
Sea $A_n$ la cantidad de dinero en la cuenta tras $n$ años. Veamos cuáles son las cantidades en la cuenta durante los primeros años.

\begin{align*}
A_1 &= 2000\cdot 1.05 \mbox{€}\\ 
A_2 &= ((2000\cdot 1.05) + 1000))1.05\mbox{€} = 2000\cdot 1.05^2 + 1000\cdot 1.05\mbox{€}\\ 
A_3 &= ((2000\cdot 1.05^2 + 1000\cdot 1.05)+1000)1.05\mbox{€}\\ 
&= 2000\cdot 1.05^3 + 1000\cdot 1.05^2 + 1000\cdot 1.05\mbox{€}
\vdots
\end{align*}

A partir de aquí, se intuye que la suma parcial de orden $n$ es 

$$
A_n = 2000\cdot 1.05^n + \sum_{i=1}^{n-1} 1000\cdot 1.05^i\mbox{€}.
$$

Como se trata de una serie geométrica, haciendo uso de la pista del @exr-series-geometricas, se puede concluir que

\begin{align*}
A_n &= 2000\cdot 1.05^n + 1000\frac{1.05^n-1}{1.05-1} - 1000\\ 
&= 2000\cdot 1.05^n + 20000 (1.05^n-1) - 1000\\ 
 &= 22000\cdot 1.05^n-21000\mbox{€}.
\end{align*}
:::

:::{#exr-distribucion-hipergeometrica}
Supongamos un experimento aleatorio que consiste en repetir una prueba con dos posibles resultados (éxito y fracaso) hasta que se obtiene el primer éxito (por ejemplo tirar una moneda hasta que sale la primera cara). La distribución de la variable aleatoria que mide el número de repeticiones hasta obtener el primer éxito se conoce como [_distribución hipergeométrica_](https://es.wikipedia.org/wiki/Distribuci%C3%B3n_hipergeom%C3%A9trica) y su función de probabilidad es 

$$
P(X=n)=(1-p)^{n-1}p,
$$

donde $p$ es la probabilidad de que ocurra éxito en cada repetición de la prueba. 

Una de las condiciones que debe cumplir una función de probabilidad de una variable aleatoria es que la suma de las probabilidades de todos los posibles valores de la variable debe ser $1$. Demostrar que la función de probabilidad de la variable hipergeométrica lo cumple.
:::

:::{.callout-tip collapse="true"}
## Solución
El conjunto de posibles valores que puede tomar la variable aleatoria $X$ es $\mathbb{N}$. Si consideramos la suma de las probabilidades de todos los posibles valores de la variable se tiene $\sum_{n=1}^\infty P(n) = \sum_{n=1}^\infty (1-p)^{n-1}p = \sum_{n=0}^\infty (1-p)^n p$, que, al tratarse de una serie geométrica de razón $(1-p)<1$, converge, y como se ha visto en el @exr-series-geometricas, la suma vale

$$
\sum_{n=1}^\infty (1-p)^n p = \frac{p}{1-(1-p)}= 1.
$$

Por tanto, cumple la condición para ser una función de probabilidad.
:::

:::{#exr-serie-conjunto-cantor}
El [conjunto de cantor](https://es.wikipedia.org/wiki/Conjunto_de_Cantor) es un subconjunto fractal del intervalo $[0,1]$ que se construye de manera recursiva eliminando en cada paso el tercio central de los intervalos que van resultando. El procedimiento sería el siguiente:

1. Quitar del intervalo $[0,1]$ el intervalo abierto $\left(\frac{1}{3},\frac{2}{3}\right)$.
2. Quitar de los intervalos restantes, los intervalos $\left(\frac{1}{9},\frac{2}{9}\right)$ y $\left(\frac{7}{9},\frac{8}{9}\right)$.
3. Quitar de los intervalos restantes, los intervalos $\left(\frac{1}{27},\frac{2}{27}\right)$, $\left(\frac{7}{27},\frac{8}{27}\right)$, $\left(\frac{19}{27},\frac{20}{27}\right)$ y $\left(\frac{25}{27},\frac{26}{27}\right)$.
4. $\ldots$

Demostrar que la longitud total de todos los intervalos eliminados es $1$, y que, a pesar de ello, el conjunto de Cantor tiene un número infinito de puntos. Se dice que este conjunto es un conjunto de medida nula, pero que ni es vacío ni numerable.
:::

:::{.callout-tip collapse="true"}
## Solución
Sea $a_n$ la longitud de los segmentos eliminados en la etapa $n$. Veamos cuál es la longitud de los segmentos eliminados en las primeras etapas.

En la primera etapa se quita el intervalo $\left(\frac{1}{3},\frac{2}{3}\right)$, y $a_1 = \frac{1}{3}$.

En la segunda etapa se quitan los intervalos $\left(\frac{1}{9},\frac{2}{9}\right)$ y $\left(\frac{7}{9},\frac{8}{9}\right)$, y por tanto, $a_n = 2\frac{1}{9}$.

En la tercera etapa se quitan los intervalos $\left(\frac{1}{27},\frac{2}{27}\right)$, $\left(\frac{7}{27},\frac{8}{27}\right)$, $\left(\frac{19}{27},\frac{20}{27}\right)$ y $\left(\frac{25}{27},\frac{26}{27}\right)$, y por tanto, $a_3=4\frac{1}{27}$.

En consecuencia, se deduce que $a_n=\frac{2^{n-1}}{3^n}$. 

Así pues, la suma de las longitudes de los intervalos quitados es $\sum_{n=1}^\infty \frac{2^{n-1}}{3^n} = \frac{1}{3}\sum_{n=1}^\infty \left(\frac{2}{3}\right)^{n-1} = \frac{1}{3}\sum_{n=0}^\infty \left(\frac{2}{3}\right)^n$, que, al ser una serie geométrica con razón $\frac{2}{3}<1$, converge, y como se ha visto en el @exr-series-geometricas, su suma vale 

$$
\frac{1}{3}\sum_{n=0}^\infty \left(\frac{2}{3}\right)^n = \frac{1}{3}\frac{1}{1-\frac{2}{3}} = 1.
$$

Así pues, el conjunto de Cantor es de medida nula. Para ver que, a pesar de ello tiene infinitos números, basta con ver que contiene, entre otros, los números $\frac{1}{3^n}$ $\forall n\in\mathbb{N}$.
:::

:::{#exr-serie-armonica-alternada}
Haciendo uso del polinomio de Taylor del logaritmo, demostrar que una serie armónica alternada $\sum \frac{(-1)^{n+1}}{n}$ converge y calcular su suma.
:::

:::{.callout-tip collapse="true"}
## Solución
El polinomio de Taylor de grado $n$ de la función $f(x)=\ln(x)$ en el punto $a=1$ es 

\begin{align*}
P^n_{f,1}(x) &= 1(x-1) - \frac{1}{2}(x-1)^2 + \frac{2!}{3!}(x-1)^3 - \frac{3!}{4!} (x-1)^4 + \cdots + (-1)^{n+1}\frac{(n-1)!}{n!}(x-1)^n \\ 
&= 1(x-1) -\frac{1}{2}(x-1)^2 + \frac{1}{3}(x-1)^3 - \frac{1}{4} (x-1)^4 + \cdots + (-1)^{n+1}\frac{1}{n}(x-1)^n 
\end{align*}

y en $x=2$ se tiene

$$
P^n_{f,1}(2) = 1 -\frac{1}{2} + \frac{1}{3} - \frac{1}{4} + \cdots + (-1)^{n+1}\frac{1}{n} = \sum_{i=1}^n \frac{(-1)^{i+1}}{i} 
$$

Por tanto, $\sum_{n=1}^\infty \frac{(-1)^{n+1}}{n} = \lim_{n\to\infty}P^n_{f,1}(2) = \ln(2)$.
:::

:::{#exr-serie-exponencial}
Haciendo uso del polinomio de Maclaurin de la función exponencial, demostrar que una serie $\sum \frac{1}{n!}$ converge y calcular su suma.
:::

:::{.callout-tip collapse="true"}
## Solución
El polinomio de Maclaurin de grado $n$ de la función $f(x)=e^x$ es

$$
P^n_{f,0}(x) = 1 + x + \frac{x^2}{2!} + \frac{x^3}{3!} + \cdots + \frac{x^n}{n!}\\ 
$$

y en $x=1$ se tiene

$$
P^n_{f,0}(1) = 1 + 1 + \frac{1}{2!} + \frac{1}{3!} + \cdots + \frac{1}{n!}\\ 
$$

Por tanto, $\sum_{n=0}^\infty \frac{1}{n!} = \lim_{n\to\infty}P^n_{f,0}(1) = e^1 = e.$
:::

:::{#exr-series-divergentes}
Demostrar que las siguientes series divergen.

a. $\sum \frac{n^2}{n+1}$

b. $\sum \cos\left(\frac{1}{n}\right)$

c. $\sum n\operatorname{sen}\left(\frac{1}{n}\right)$

d. $\sum \frac{1}{2n}$
:::

:::{.callout-tip collapse="true"}
## Solución
a. Como $\lim_{n\to\infty} \frac{n^2}{n+1} = \infty$, por la [condición de convergencia](https://aprendeconalf.es/analisis-manual/08-series.html#thm-condicion-convergencia-series), la serie $\sum \frac{n^2}{n+1}$ diverge.

b. Como $\lim_{n\to\infty}  \cos\left(\frac{1}{n}\right)=1\neq 0$, por la [condición de convergencia](https://aprendeconalf.es/analisis-manual/08-series.html#thm-condicion-convergencia-series), la serie $\sum \cos\left(\frac{1}{n}\right)$ diverge.

c. Como $\lim_{n\to\infty}  n\operatorname{sen}\left(\frac{1}{n}\right)=1\neq 0$, por la [condición de convergencia](https://aprendeconalf.es/analisis-manual/08-series.html#thm-condicion-convergencia-series), la serie $\sum n\operatorname{sen}\left(\frac{1}{n}\right)$ diverge.

d. $\sum \frac{1}{2n} = \frac{1}{2}\sum \frac{1}{n}$ y como la serie armónica $\sum \frac{1}{n}$ diverge, la serie $\sum \frac{1}{2n}$ también.
:::

:::{#exr-serie-telescopica-convergente}
Demostrar que $\sum_{n=1}^\infty \frac{1}{n(n+1)} = 1$.
:::

:::{.callout-note collapse="true"}
## Pista
Descomponer el término general de la sucesión subyacente a la serie en fraccione simples.
:::

:::{.callout-tip collapse="true"}
## Solución
El término general de la sucesión se puede descomponer en fracciones simples de la siguiente manera $\frac{1}{n(n+1)} = \frac{1}{n}-\frac{1}{n+1}$, que es una serie telescópica,  de modo que la suma parcial de los $n$ primeros términos de la serie es

\begin{align*}
A_n &= \left(1-\frac{1}{2}\right)+\left(\frac{1}{2}-\frac{1}{3}\right)+\left(\frac{1}{3}-\frac{1}{4}\right)+\cdots +\left(\frac{1}{n}-\frac{1}{n+1}\right) = 1-\frac{1}{n+1}
\end{align*}

Así pues, 

$$
\sum_{n=1}^\infty \frac{1}{n(n+1)} = \lim_{n\to\infty} A_n  = \lim_{n\to\infty} 1-\frac{1}{n+1} = 1.
$$
:::

:::{#exr-series-telescopicas}
Estudiar la convergencia de las siguientes series telescópicas.

a. $\sum \cos(n^2)-\cos((n+1)^2)$

b. $\sum \operatorname{sen}\left(\frac{1}{n}\right)-\operatorname{sen}\left(\frac{1}{n+1}\right)$ 

c. $\sum \ln\left(\frac{n+1}{n}\right)$

d. $\sum_{n\geq 2} \frac{2}{n^2-1}$
:::

:::{.callout-tip collapse="true"}
## Solución
a. Como se trata de una serie telescópica, se tiene que la suma parcial de orden $n$ es 

    \begin{align*}
    A_n &= \sum_{i=1}^n \cos(i^2)-\cos((i+1)^2)\\  
    &= \cos(1)-\cos(2^2)+\cos(2^2)-\cos(3^2)+\cdots +\cos(n^2)-\cos((n+1)^2)\\  
    &= \cos(1)-\cos((n+1)^2).
    \end{align*}

    Así pues, 

    \begin{align*}
    \sum_{n=1}^\infty \cos(n^2)-\cos((n+1)^2) &= \lim_{n\to\infty} A_n = \lim_{n\to\infty} \cos(1)-\cos((n+1)^2) \\ 
    &= \cos(1)-\lim_{n\to\infty} \cos((n+1)^2).
    \end{align*}

    Pero como no existe $\lim_{n\to\infty} \cos((n+1)^2)$, la serie no converge.

b. Como se trata de una serie telescópica, se tiene que la suma parcial de orden $n$ es 

    \begin{align*}
    A_n &= \sum_{i=1}^n \operatorname{sen}\left(\frac{1}{i}\right)- \operatorname{sen}\left(\frac{1}{i+1}\right)\\  
    &=  \operatorname{sen}(1)- \operatorname{sen}\left(\frac{1}{2}\right)+ \operatorname{sen}\left(\frac{1}{2}\right)- \operatorname{sen}\left(\frac{1}{3}\right)+ \cdots +  \operatorname{sen}\left(\frac{1}{n}\right)- \operatorname{sen}\left(\frac{1}{n+1}\right)\\  
    &= \operatorname{sen}(1)- \operatorname{sen}\left(\frac{1}{n+1}\right).
    \end{align*}

    Así pues, 

    \begin{align*}
    \sum_{n=1}^\infty  \operatorname{sen}\left(\frac{1}{n}\right) - \operatorname{sen}\left(\frac{1}{n+1}\right) &= \lim_{n\to\infty} A_n = \lim_{n\to\infty} \operatorname{sen}(1)- \operatorname{sen}\left(\frac{1}{n+1}\right) \\ 
    &= \operatorname{sen}(1)- \lim_{n\to\infty}\operatorname{sen}\left(\frac{1}{n+1}\right) = \operatorname{sen}(1),
    \end{align*}

    y, por tanto, la serie converge a $\operatorname{sen}(1)$.

c. $\sum \ln\left(\frac{n+1}{n}\right) = \sum \ln(n+1)-\ln(n)$ que de nuevo es una serie telescópica, por lo que su suma parcial de orden $n$ es 

    \begin{align*}
    A_n &= \sum_{i=1}^n \ln(i+1)-\ln(i) \\ 
    &= \ln(2)-\ln(1)+\ln(3)-\ln(2)+\ln(4)-\ln(3)+\cdots +\ln(n+1)-\ln(n) \\ 
    &= \ln(n+1)-\ln(1) = \ln(n+1).
    \end{align*}

    Así pues, 

    $$
    \sum_{n=1}^\infty \ln\left(\frac{n+1}{n}\right) = \lim_{n\to\infty} A_n = \lim_{n\to\infty} \ln(n+1) =\infty,
    $$

    y, por tanto, la serie diverge.

d. $\sum_{n\geq 2} \frac{2}{n^2-1} = \sum_{n\geq 2} \frac{1}{n-1}-\frac{1}{n+1}$, que también es una serie telescópica, cuya suma parcial de orden $n$ es

    \begin{align*}
    A_n &= \sum_{i=2}^n \frac{1}{i-1}-\frac{1}{i+1} \\ 
    &= 1-\frac{1}{3}+\frac{1}{2}-\frac{1}{4}+\frac{1}{3}-\frac{1}{5}+\cdots + \frac{1}{n-1}-\frac{1}{n+1} \\ 
    &= 1+\frac{1}{2}-\frac{1}{n+1} = \frac{3}{2}-\frac{1}{n+1}.
    \end{align*}

    Así pues, 
    
    $$
    \sum_{n=2}^\infty \frac{1}{n-1}-\frac{1}{n+1} = \lim_{n\to\infty} A_n = \lim_{n\to\infty}\frac{3}{2}-\frac{1}{n+1} = \frac{3}{2}-\lim_{n\to\infty}\frac{1}{n+1} =\frac{3}{2},
    $$

    y, por tanto, la serie converge a $\frac{3}{2}$.
:::

:::{#exr-comparacion-series}
Estudiar la convergencia de las siguientes series comparándolas con otras conocidas.

:::: {.columns}
::: {.column}
a. $\sum \frac{2n}{4n^3-n+1}$

b. $\sum \frac{\ln(n)}{n}$

c. $\sum \frac{3^n}{2^n+1}$

d. $\sum \frac{n+1}{\sqrt{n^3}}$
:::

::: {.column}
e. $\sum \frac{e^{1/n}}{n}$

f. $\sum \operatorname{sen}\left(\frac{1}{n}\right)$

g. $\sum \frac{n+1}{n!}$

h. $\sum \frac{n^n}{n!}$
:::
:::
:::

:::{.callout-tip collapse="true"}
## Solución
a.  $\frac{2n}{4n^3-n+1}>0$ $\forall n\in\mathbb{N}$, por lo que se trata de una serie de términos positivos. Como $4n^3-n+1>4n^3-n>0$ $\forall n\mathbb{N}$ se tiene que

    $$
    \frac{2n}{4n^3-n+1}<\frac{2n}{4n^3-n}=\frac{2}{4n^2-1} = \frac{2}{(2n+1)(2n-1)} = \frac{1}{2n-1}-\frac{1}{2n+1}\ \forall n\in\mathbb{N}.
    $$

    Así pues, por el criterio de comparación de series, $\sum \frac{2n}{4n^3-n+1}$ converge sí $\sum \frac{1}{2n-1}-\frac{1}{2n+1}$ converge. Pero esta última serie es una serie telescópica, y como $\lim_{n\to\infty} \frac{1}{2n-1}=0$, converge, de manera que $\sum \frac{2n}{4n^3-n+1}$ también converge.

b. $\frac{\ln(n)}{n}\geq 0$ $\forall n\in\mathbb{N}$, por lo que se trata de una serie de términos positivos. Como $\ln(n)>1$ $\forall n\geq 3$, se tiene que $\frac{\ln(n)}{n}>\frac{1}{n}$ $\forall n\geq 3$, y como $\sum \frac{1}{n}$ es la serie armónica, que diverge, por el criterio de la comparación de series, $\sum \frac{\ln(n)}{n}$ también diverge.

c. $\frac{3^n}{2^n+1}>0$ $\forall n\in\mathbb{N}$ por lo que se trata de una serie de términos positivos. Como $2^n+1>2^n$ $\forall n\in\mathbb{N}$, se tiene que $\frac{3^n}{2n+1}<\frac{3^n}{2^n}=\left(\frac{3}{2}\right)^n$ $\forall n\in\mathbb{N}$. Y como $\sum \left(\frac{3}{2}\right)^n$ diverge al ser una serie geométrica de razón $\frac{3}{2}>1$, por el criterio de comparación de series se tiene que $\sum \frac{3^n}{2^n+1}$ también diverge.

d. $\frac{n+1}{\sqrt{n^3}}>0$ $\forall n\in\mathbb{N}$ por lo que se trata de una serie de términos positivos. Por otro lado, 

    $$
    \sum \frac{n+1}{\sqrt{n^3}} = \sum \frac{n+1}{n^{3/2}} = \sum \left(\frac{n}{n^{3/2}} + \frac{1}{n^{3/2}}\right) = \sum \frac{1}{n^{1/2}} + \sum \frac{1}{n^{3/2}}.
    $$

    Como $\sum \frac{1}{n^{1/2}}$ es una serie $p$ con $p<1$, diverge, y por tanto, $\sum \frac{n+1}{\sqrt{n^3}}$ también diverge.

e. $\frac{e^{1/n}}{n}>0$ $\forall n\in\mathbb{N}$ por lo que se trata de una serie de términos positivos. Como $e^{1/n}>1$ $\forall n\in\mathbb{N}$ se tiene que $\frac{e^{1/n}}{n}>\frac{1}{n}$ $\forall n\in\mathbb{N}$, y como $\sum \frac{1}{n}$ es la serie armónica, que diverge, por el criterio de la comparación de series, $\sum \frac{e^{1/n})}{n}$ también diverge.

f. $\operatorname{sen}\left(\frac{1}{n}\right)>0$ $\forall n\in\mathbb{N}$ por lo que se trata de una serie de términos positivos. Haciendo el cambio de variable $x=\frac{1}{n}$, se tiene

    $$
    \lim_{n\to\infty}\frac{\operatorname{sen}\left(\frac{1}{n}\right)}{\frac{1}{n}} = \lim_{x\to 0}\frac{\operatorname{sen}(x)}{x} = 1,
    $$

    al ser $\operatorname{sen}(x)$ y $x$ infinitésimos equivalentes en $0$. Así pues, por el criterio del cociente, se tiene que $\sum \operatorname{sen}\left(\frac{1}{n}\right)$ converge si y solo si $\sum \frac{1}{n}$ converge, pero $\sum \frac{1}{n}$ es la serie armónica, que diverge, y por tanto, $\sum \operatorname{sen}\left(\frac{1}{n}\right)$ también diverge.

g. $\frac{n+1}{n!}>0$ $\forall n\in\mathbb{N}$ por lo que se trata de una serie de términos positivos. Por otro lado, se tiene

    $$
    \sum \frac{n+1}{n!} = \sum \frac{n}{n!}+\frac{1}{n!} = \sum \frac{1}{{n-1}!}+\sum \frac{1}{n!},
    $$

    y como se ha visto en el @exr-serie-exponencial, tanto $\sum \frac{1}{(n-1)!}$ como $\sum \frac{1}{n!}$ convergen, por lo que $\sum \frac{n+1}{n!}$ también converge.

h. $\frac{n^n}{n!}>0$ $\forall n\in\mathbb{N}$ por lo que se trata de una serie de términos positivos. Por otro lado, se tiene

    $$ \frac{n^n}{n!} = \frac{n}{n} \frac{n}{n-1} \frac{n}{n-2} \cdots \frac{n}{1}\geq n \ \forall n\in \mathbb{N}.
    $$

    Y como $\sum n$ diverge, por el criterio de comparación de series, $\sum \frac{n^n}{n!}$ también diverge.
:::

:::{#exr-criterio-cociente}
Demostrar que si $\sum a_n$ y $\sum b_n$ son dos series de términos positivos entonces se cumple que 

a. Si $\lim_{n\to\infty} \frac{a_n}{b_n} = 0$ y $\sum b_n$ converge, entonces $\sum a_n$ también converge.

b. Si $\lim_{n\to\infty} \frac{a_n}{b_n} = \infty$ y $\sum b_n$ diverge, entonces $\sum a_n$ también diverge.
:::

:::{.callout-tip collapse="true"}
## Solución
a. Supongamos que $\lim_{n\to\infty} \frac{a_n}{b_n}=0$. Entonces, para $\varepsilon=1$ existe $k\in\mathbb{N}$ tal que $\left|\frac{a_n}{b_n}\right|=\frac{a_n}{b_n}<1$ $\forall n\geq k$, y por tanto, $a_n<b_n$ $\forall n\geq k$. Así pues, por el criterio de comparación de series, si $\sum_{n\geq k} b_n$ converge, $\sum_{n\geq k} a_n$ también, y como un número finito de términos no influye en la convergencia de una serie, $\sum a_n$ converge.

b. Supongamos que $\lim_{n\to\infty} \frac{a_n}{b_n}=\infty$. Entonces, para $\varepsilon=1$ existe $k\in\mathbb{N}$ tal que $\left|\frac{a_n}{b_n}\right|=\frac{a_n}{b_n}>1$ $\forall n\geq k$, y por tanto, $a_n>b_n$ $\forall n\geq k$. Así pues, por el criterio de comparación de series, si $\sum_{n\geq k} b_n$ diverge, $\sum_{n\geq k} a_n$ también, y como un número finito de términos no influye en la convergencia de una serie, $\sum a_n$ diverge.
:::

:::{#exr-series-positivas-convergentes}
Dada una serie de términos positivos $\sum a_n$ convergente, estudiar si las siguientes series convergen.

a. $\sum a_n^2$

b. $\sum \frac{1}{a_n^3}$

b. $\sum \ln(1+a_n)$

c. $\sum \operatorname{sen}(a_n)$
:::

:::{.callout-tip collapse="true"}
## Solución
a. Por el criterio de divergencia, como $\sum a_n$ converge, se tiene que $\lim_{n\to\infty} a_n = 0$. Por otro lado, $\lim_{n\to\infty}\frac{a_n^2}{a_n} = \lim_{n\to\infty} a_n = 0$, y por lo visto en el @exr-criterio-cociente, como $\sum a_n$ converge, $\sum a_n^2$ también.

b. $\lim_{n\to\infty}\frac{a_n^3}{a_n} = \lim_{n\to\infty} a_n^2 = 0$, ya que, según el apartado anterior $\sum a_n^2$ converge, y por lo visto en el @exr-criterio-cociente, como $\sum a_n$ converge, $\sum a_n^3$ también. Finalmente, como $\sum a_n^3$ converge, la serie de los inversos $\sum a_n^{-3}$ diverge.

c. Por el criterio de divergencia, como $\sum a_n$ converge, se tiene que $\lim_{n\to\infty} a_n = 0$, y haciendo el cambio de variable $x=a_n$, se tiene 

    $$
    \lim_{n\to\infty} \frac{\ln(1+a_n)}{a_n} = \lim_{x\to 0}\frac{\ln(1+x)}{x} = 1,
    $$

    ya que $\ln(1+x)$ y $x$ son infinitésimos equivalentes en $0$. Por tanto, por el criterio del cociente, $\sum \ln(1+a_n)$ también converge.

d.  Por el criterio de divergencia, como $\sum a_n$ converge, se tiene que $\lim_{n\to\infty} a_n = 0$, y haciendo el cambio de variable $x=a_n$, se tiene 

    $$
    \lim_{n\to\infty} \frac{\operatorname{sen}(a_n)}{a_n} = \lim_{x\to 0}\frac{\operatorname{sen}(x)}{x} = 1,
    $$

    ya que $\operatorname{sen}(x)$ y $x$ son infinitésimos equivalentes en $0$. Por tanto, por el criterio del cociente, $\sum \operatorname{sen}(a_n)$ también converge.
:::

:::{#exr-series-alternadas}
Estudiar la convergencia de las siguientes series alternadas.

a. $\sum \frac{(-1)^{n-1}}{2n-1}$

b. $\sum (-1)^ne^{-n}$

c. $\sum (-1)^n\operatorname{sen}\left(\frac{\pi}{n}\right)$

d. $\sum (-1)^n\left(\frac{1}{\sqrt{n+1}}-\frac{1}{\sqrt{n}}\right)$
:::

:::{.callout-tip collapse="true"}
## Solución
a. $\left(\frac{1}{2n-1}\right)_{n=1}^\infty$ es una sucesión monótona decreciente, ya que $\frac{1}{2n-1}>\frac{1}{2(n+1)-1}=\frac{1}{2n+1}$ $\forall n\in\mathbb{N}$. Como además $\lim_{n\to\infty} \frac{1}{2n-1} = 0$, por el criterio de la serie alternada se tiene que $\sum \frac{(-1)^{n-1}}{2n-1}$ converge.

b. $(e^{-n})_{n=1}^\infty$ es una sucesión monótona decreciente, ya que $e^{-n}>e^{-(n+1)}$ $\forall n\in\mathbb{N}$. Como además $\lim_{n\to\infty} e^{-n} = 0$, por el criterio de la serie alternada se tiene que $\sum (-1)^ne^{-n}$ converge.

c. $\left(\operatorname{sen}\left(\frac{\pi}{n}\right)\right)_{n=1}^\infty$ es una sucesión monótona decreciente, ya que $\operatorname{sen}\left(\frac{\pi}{n}\right)>\operatorname{sen}\left(\frac{\pi}{n+1}\right)$ $\forall n\geq 2$. Como además $\lim_{n\to\infty} \operatorname{sen}\left(\frac{\pi}{n}\right) = 0$, por el criterio de la serie alternada se tiene que  $\sum (-1)^n\operatorname{sen}\left(\frac{\pi}{n}\right)$ converge.

d. Sea $A_n$ la suma parcial de orden $n$ de la serie $\sum (-1)^n\left(\frac{1}{\sqrt{n+1}}-\frac{1}{\sqrt{n}}\right)$. Si desarrollamos las primeras sumas parciales se tiene 

    \begin{align*}
    A_1 &= \frac{-1}{\sqrt{2}}+\frac{1}{\sqrt{1}}\\
    A_2 &= \frac{-1}{\sqrt{2}}+\frac{1}{\sqrt{1}} + \frac{1}{\sqrt{3}}-\frac{1}{\sqrt{2}} = 1 - \frac{2}{\sqrt{2}} + \frac{1}{\sqrt{3}}\\
    A_3 &= 1 - \frac{2}{\sqrt{2}} + \frac{1}{\sqrt{3}} -\frac{1}{\sqrt{4}} +\frac{1}{\sqrt{3}} =  1 - \frac{2}{\sqrt{2}} + \frac{2}{\sqrt{3}} -\frac{1}{\sqrt{4}} \\
    A_3 &= 1 - \frac{2}{\sqrt{2}} + \frac{2}{\sqrt{3}} -\frac{1}{\sqrt{4}} + \frac{1}{\sqrt{5}} -\frac{1}{\sqrt{4}} = 1 - \frac{2}{\sqrt{2}} + \frac{2}{\sqrt{3}} -\frac{2}{\sqrt{4}} + \frac{1}{\sqrt{5}}\\
    \vdots\\
    A_n &= 1 + 2\sum_{i=1}^n \frac{(-1)^n}{\sqrt{n}}
    \end{align*}

    Como la sucesión $\left(\frac{1}{\sqrt{n}}\right)_{n=1}^\infty$ es monótona decreciente, ya que $\frac{1}{\sqrt{n}}>\frac{1}{\sqrt{n+1}}$ $\forall n\in\mathbb{N}$, y $\lim_{n\to\infty} \frac{1}{\sqrt{n}} = 0$, por el criterio de la serie alternada se tiene que $\sum \frac{(-1)^n}{\sqrt{n}}$ converge, y por tanto, $\sum (-1)^n\left(\frac{1}{\sqrt{n+1}}-\frac{1}{\sqrt{n}}\right) = 1 + 2\sum \frac{(-1)^n}{\sqrt{n}}$ también converge.
:::

:::{#exr-muelle-amortiguado}
El movimiento de un [muelle amortiguado](https://upload.wikimedia.org/wikipedia/commons/f/fa/Spring-mass_under-damped.gif) con un peso colgado de él es oscilante. Si la posición que ocupa el peso en cada periodo de oscilación $n$ viene dado por la serie $\sum (-1)^{n-1}e^{-n/2}$, ¿llegará a estabilizarse en una posición de equilibrio a largo plazo?
:::

:::{.callout-tip collapse="true"}
## Solución
$(e^{-n/2})_{n=1}^\infty$ es una sucesión monótona decreciente, ya que $e^{-n/2}>e^{-(n+1)/2}$ $\forall n\in\mathbb{N}$. Como además $\lim_{n\to\infty} e^{-n/2} = 0$, por el criterio de la serie alternada se tiene que $\sum (-1)^{n-1}e^{-n/2}$ converge, así que el peso colgado del muelle se estabilizará a largo plazo en la posición $\sum (-1)^{n-1}e^{-n/2}$.
:::

:::{#exr-convergencia-absoluta}
Estudiar la convergencia absoluta de las siguientes series.

:::: {.columns}
::: {.column}
a. $\sum \frac{(-2)^n}{n^2}$.

b. $\sum \frac{n}{3^n}$

c. $\sum \frac{\operatorname{sen}(n)}{n^2}$.
:::

::: {.column}
d. $\sum \frac{(-1)^n}{\ln(n)}$

e. $\sum \left(\frac{n^2+1}{2n^2-1}\right)^n$

d. $\sum \frac{n!}{n^n}$
:::
:::
:::

:::{.callout-tip collapse="true"}
## Solución
a. Como

    $$
    \lim_{n\to\infty} \left|\frac{a_{n+1}}{a_n}\right| = \lim_{n\to\infty} \frac{\frac{2^{n+1}}{(n+1)^2}}{\frac{2^n}{n^2}} = \lim_{n\to\infty}\frac{2n^2}{(n+1)^2} = 2 >1,
    $$

    por el criterio de la razón, se tiene que $\sum \frac{(-2)^n}{n^2}$ diverge.

b. Como

    $$
    \lim_{n\to\infty} \left|\frac{a_{n+1}}{a_n}\right| = \lim_{n\to\infty} \frac{\frac{n+1}{3^{n+1}}}{\frac{n}{3^n}} = \lim_{n\to\infty}\frac{n+1}{3n} = \frac{1}{3} <1,
    $$

    por el criterio de la razón, se tiene que $\sum \frac{n}{3^n}$ es absolutamente convergente.

c. Como $\left|\frac{\operatorname{sen}(n)}{n^2}\right|< \frac{1}{n^2}$ $\forall n\in\mathbb{N}$, y $\sum \frac{1}{n^2}$ converge al ser una serie $p$ con $p=2>1$, por el criterio de comparación de series, $\sum \left|\frac{\operatorname{sen}(n)}{n^2}\right|$ converge, y por tanto, $\sum \frac{\operatorname{sen}(n)}{n^2}$ es absolutamente convergente.

d. $\sum \left|\frac{(-1)^n}{\ln(n)}\right|= \sum \frac{1}{\ln(n)}$ $\forall n>1$, y como $\frac{1}{\ln(n)}>\frac{1}{n}$ $\forall n>1$, por el criterio de comparación de series, $\sum \frac{1}{\ln(n)}$ diverge ya que $\sum \frac{1}{n}$ diverge. Por tanto, $\sum \frac{(-1)^n}{\ln(n)}$ no es absolutamente converge.

e. Como 

    $$
    \lim_{n\to\infty} \sqrt[n]{\left|\left(\frac{n^2+1}{2n^2-1}\right)^n\right|} = \lim_{n\to\infty} \frac{n^2+1}{2n^2-1} = \frac{1}{2}<1,
    $$

    por el criterio de la razón, se tiene que $\sum \left(\frac{n^2+1}{2n^2-1}\right)^n$ es absolutamente convergente.

f. Como 

    \begin{align*}
    \lim_{n\to\infty} \left|\frac{a_{n+1}}{a_n}\right| &= \lim_{n\to\infty} \frac{\frac{(n+1)!}{(n+1)^{n+1}}}{\frac{n!}{n^n}} = \lim_{n\to\infty} \frac{\frac{(n+1)n!}{(n+1)(n+1)^n}}{\frac{n!}{n^n}} \\
    & = \lim_{n\to\infty} \frac{n^n}{(n+1)^n} = \lim_{n\to\infty} \left(\frac{n}{n+1}\right)^n = \frac{1}{e}<1,
    \end{align*}

    por el criterio de la razón, se tiene que $\sum \frac{n!}{n^n}$ es absolutamente convergente.
:::

:::{#exr-radio-convergencia-raiz-razon}
Demostrar que el radio de convergencia de una serie de potencias $\sum c_nx^n$ se puede calcular mediante las siguientes fórmulas

$$
R = \frac{1}{\lim_{n\to\infty} \sqrt[n]{|c_n|}} \quad \mbox{o}\quad R = \lim_{n\to\infty} \left|\frac{c_n}{c_{n+1}}\right|.
$$
:::

:::{.callout-tip collapse="true"}
## Solución
Para probar la validez de la primera fórmula utilizaremos el criterio de la raíz para convergencia absoluta de series. 

$$
\lim_{n\to\infty} \sqrt[n]{|c_nx^n|} = |x| \lim_{n\to\infty}\sqrt[n]{|c_n|} < 1 \Leftrightarrow |x| < \frac{1}{\lim_{n\to\infty} \sqrt[n]{|c_n|}}.
$$

Y para probar la validez de la segunda fórmula utilizaremos el criterio de la razón para la convergencia absoluta de series.

$$
\lim_{n\to\infty} \left|\frac{c_{n+1}x^{n+1}}{c_nx^n}\right| = |x|\lim_{n\to\infty} \left|\frac{c_{n+1}}{c_n}\right| < 1 \Leftrightarrow |x| < \frac{1}{\lim_{n\to\infty} \left|\frac{c_{n+1}}{c_n}\right|} = \lim_{n\to\infty} \left|\frac{c_n}{c_{n+1}}\right|.
$$
:::

:::{#exr-radio-convergencia}
Calcular el radio de convergencia y el dominio de convergencia puntual de las siguientes series de potencias.

:::: {.columns}
::: {.column}
a. $\sum nx^n$

b. $\sum \frac{(-1)^nx^n}{\sqrt{n}}$

c. $\sum n!(x-1)^n$
:::

::: {.column}
d. $\sum \frac{(x-2)^n}{n^3}$

e. $\sum \frac{n!(x-3)^n}{n^n}$

f. $\sum \operatorname{sen}(1/n) (x+1)^n$
:::
:::
:::

:::{.callout-tip collapse="true"}
## Solución

:::

:::{#exr-suma-serie-potencias-exponencial}
Demostrar que la serie de potencias $\sum \frac{x^n}{n!}$ es absolutamente convergente para cualquier $x\in\mathbb{R}$.

Demostrar también que la función $f(x)=\sum_{n=0}^\infty \frac{x^n}{n!}$ cumple la ecuación diferencial $f'(x)=f(x)$. ¿Qué otras funciones conoces que la cumplen?

Demostrar finalmente que $f(x)=e^x$.
:::

:::{.callout-tip collapse="true"}
## Solución
Como 

\begin{align*}
\lim_{n\to\infty} \left|\frac{a_{n+1}}{a_n}\right| &= \lim_{n\to\infty} \frac{\frac{x^{n+1}}{(n+1)!}}{\frac{x^n}{n!}} = \lim_{n\to\infty} \frac{\frac{|xx^n|}{(n+1)n!}}{\frac{|x^n|}{n!}} \\
& = \lim_{n\to\infty} \frac{|x|}{n+1} = 0 \ \forall x\in\mathbb{R},
\end{align*}

por el criterio de la razón, se tiene que $\sum \frac{x^n}{n!}$ es absolutamente convergente $\forall x\in\mathbb{R}$.

Sea $A_n(x)$ la función de la suma parcial de orden $n$ de la serie anterior para cualquier $x\in\mathbb{R}$, es decir,

$$
A_n(x) = 1 + x + \frac{x^2}{2!} + \frac{x^3}{3!} + \frac{x^4}{4!} + \cdots +\frac{x^n}{n!}
$$

Entonces, su derivada vale

\begin{align*}
A_n'(x) &= (1)' + (x)' + \left(\frac{x^2}{2!}\right)' + \left(\frac{x^3}{3!}\right)' + \left(\frac{x^4}{4!}\right)' + \cdots + \left(\frac{x^n}{n!}\right)'\\
&= 0 + 1 + \frac{2x}{2!} + \frac{3x^2}{3!} + \frac{4x^3}{4!} + \cdots +\frac{nx^{n-1}}{n!} \\
&=  1 + x + \frac{x^2}{2!} + \frac{x^3}{3!} + \frac{x^4}{4!} + \cdots +\frac{x^{n-1}}{(n-1)!} = A_{n-1}(x)
\end{align*}

Así pues, si tomamos la función $f(x)=\sum_{n=0}^\infty \frac{x^n}{n!} = \lim_{n\to\infty} A_n(x)$, su derivada vale 

$$
f'(x) = \lim_{n\to\infty} A_n'(x) = \lim_{n\to\infty} A_{n-1}(x) = \lim_{n\to\infty} A_{n}(x) = f(x).
$$

Por tanto, la función $f(x)=\sum_{n=0}^\infty \frac{x^n}{n!}$ cumple la ecuación diferencial $f'(x)=f(x)$.

Otra función conocida que cumple esa ecuación diferencial es $g(x)=e^x$.

Veamos que $f(x)=e^x$.
:::

:::{#exr-suma-serie-potencias}
Usar el resultado del ejercicio anterior para calcular la suma de la serie de potencias $\sum \frac{(x+2)^n}{(n+1)!}$.
:::

:::{.callout-tip collapse="true"}
## Solución
$$
\sum_{n=0}^\infty \frac{(x+2)^n}{(n+1)!} = \sum_{n=0}^\infty \frac{(x+2)^{n+1}}{(x+2)(n+1)!} = \frac{1}{x+2}\sum_{n=1}^\infty \frac{(x+2)^n}{n!} = \frac{e^{x+2}-1}{x+2}.
$$
:::

:::{#exr-serie-poisson}
La [_distribución de Poisson_](https://es.wikipedia.org/wiki/Distribuci%C3%B3n_de_Poisson) es una de las distribuciones de probabilidad más importantes, ya que explica la probabilidad de que ocurra un número determinado de fenómenos puntuales en un soporte continuo (como por ejemplo el número de llamadas telefónicas que llegan a un servicio de atención al cliente en un intervalo de tiempo). Su función de probabilidad es

$$
P(n)= e^{-\lambda}\frac{\lambda^n}{n!}\ \forall n\in \mathbb{N},
$$

donde $\lambda>0$ es su media.

Demostrar que esta función es una función de masa de probabilidad.
:::

:::{.callout-tip collapse="true"}
## Solución
El conjunto de posibles valores que puede tomar la variable aleatoria $X$ es $\mathbb{N}\cup \{0\}$. Si consideramos la suma de las probabilidades de todos los posibles valores de la variable se tiene 

$$
\sum_{n=0}^\infty P(n) = \sum_{n=0}^\infty e^{-\lambda}\frac{\lambda^n}{n!} = e^{-\lambda}\sum_{n=0}^\infty \frac{\lambda^n}{n!}.
$$

Como se ha visto en el @exr-suma-serie-potencias-exponencial, $\sum_{n=0}^\infty \frac{x^n}{n!}=e^x$ $\forall x\in\mathbb{R}$, en particular se tiene que $\sum_{n=0}^\infty \frac{\lambda^n}{n!}=e^\lambda$, por lo que finalmente se tiene

$$
\sum_{n=0}^\infty P(n) = e^{-\lambda}e^{\lambda} = 1,
$$

y se cumple la condición para ser una función de probabilidad.
:::

:::{#exr-serie-taylor}
Calcular la serie de Taylor de las siguientes funciones en los puntos dados.

a. $f(x)=\cos(x)$ en $a=\pi$.

b. $g(x)=\ln(x)$ en $a=1$.

c. $h(x)=\frac{1}{\sqrt{x}}$ en $a=1$.
:::

:::{.callout-tip collapse="true"}
## Solución

:::

:::{#exr-serie-binomial}
Construir la serie de Maclaurin de la función $f(x)= (1+x)^k$ para cualquier $k\in\mathbb{R}$ y estudiar su dominio de convergencia.
¿Qué serie se obtiene cuando $k\in\mathbb{N}$?
:::

:::{.callout-tip collapse="true"}
## Solución

:::

:::{#exr-serie-arcotangente}
Calcular la serie de Maclaurin de la función $f(x)=\operatorname{arctg}(x)$ y utilizarla para obtener una serie cuya suma sea $\pi$.
:::

:::{.callout-tip collapse="true"}
## Solución

:::

:::{#exr-limite-tangente}
Usando desarrollos de Taylor, calcular los siguientes límites.

a. $\lim_{x\to 0}\frac{\ln(1+x)-x}{x^2}$

b. $\lim_{x\to 0}\frac{\operatorname{tg}(x)-x}{x^3}$
:::

:::{.callout-tip collapse="true"}
## Solución

:::