---
title: Integrales de funciones de varias variables
lang: es
---

:::{#exr-sumas-riemann-n-dimensional}
Calcular la suma inferior y superior de Riemann de la función $f(x,y)=12-x^2-2y$ en el intervalo $I=[0,2]\times[0,2]$ tomando $4$ subintervalos de igual tamaño. 
:::

:::{.callout-tip collapse="true"}
## Solución
Para dividir el intervalo $I=[0,2]\times[0,2]$ en 4 subintervalos de igual tamaño basta tomar la partición $P=\{0,1,2\}\times\{0,1,2\}$ que define los subintervalos $I_1=[0,1]\times [0,1]$, $I_2=[0,1]\times [1,2]$, $I_3=[1,2]\times [0,1]$ y $I_4=[1,2]\times [1,2]$.

![Partición del intervalo $[0,2]\times [0,2]$ en 4 subintervalos de igual tamaño.](img/integrales-funciones-varias-variables/partici%C3%B3n-4-subintervalos){width=250}

Como se observa todos los subintervalos tienen area 1. Además, como $f$ es decreciente tanto en $x$ como en $y$ en el intervalo $I$, alcanzará el mínimo en el extremo superior derecho de cada uno de estos subintervalos, y el máximo en el extremo inferior izquierdo. Así pues, la suma inferior de Riemann de esta partición es

$$
s(f,P) 
= f(1,1) + f(1,2) + f(2,1) + f(2,2)
= 9 + 7 + 6 + 4
= 26,
$$

y la suma superior de Riemann es

$$
S(f,P) 
= f(0,0) + f(0,1) + f(1,0) + f(1,1)
= 12 + 11 + 10 + 9 
= 42.
$$
:::

:::{#exr-integral-inferior-superior-riemann-n-dimensional}
Calcular la integral inferior y superior de Riemann de la función $f(x,y)=12-x^2-2y$ en el intervalo $I=[0,2]\times[0,2]$. ¿Es $f$ integrable Riemann en el intervalo $I$? ¿Cuánto vale la integral?
:::

:::{.callout-tip collapse="true"}
## Solución
Consideremos la partición $P_n = \left\{\frac{2i}{n}: i=1,\ldots,n\right\}$ que divide el intervalo $[0,2]$ en $n$ subintervalos iguales, y la partición $P=P_n\times P_n$ del intervalo $I=[0,2]\times[0,2]$ en $n^2$ subintervalos de igual tamaño.

La suma inferior de Riemann de $f$ es 

$$
s(f,P) = \sum_{i=1}^n\sum_{j=1}^n m_{i,j} (x_i-x_{i-1})(y_j-y_{j-1}).
$$

Como los subintervalos de $P_n$ tienen todos amplitud $2/n$, se tiene que $(x_i-x_{i-1}) = (y_j-y_{j-1}) = 2/n$, de modo que todos los subintervalos tienen area $(2/n)^2$. Y como la función es decreciente tanto en $x$ como en $y$ en el intervalo $I$, el mínimo de la función en el intervalo $[x_i,x_{i-1}]\times[y_j,y_{j-1}]$ se alcanzará en el extremo superior derecho, es decir, en el punto $(x_i,y_j)$, por lo que la suma inferior de Riemann puede es

\begin{align*}
s(f,P) 
&= \sum_{i=1}^n\sum_{j=1}^n f(x_i,y_j) \frac{4}{n^2}
= \sum_{i=1}^n\sum_{j=1}^n (12-x_i^2-2y_j) \frac{4}{n^2} \\
&= \sum_{i=1}^n\sum_{j=1}^n \left(12-\left(\frac{2i}{n}\right)^2-2\frac{2j}{n}\right) \frac{4}{n^2} \\
&= \frac{4}{n^2} \sum_{i=1}^n\sum_{j=1}^n 12-\frac{4i^2}{n^2}-\frac{4j}{n} \\
&= \frac{16}{n^2} \sum_{i=1}^n\sum_{j=1}^n 3-\frac{i^2}{n^2}-\frac{j}{n} \\
&= \frac{16}{n^2} \left(\sum_{i=1}^n\sum_{j=1}^n 3- \sum_{i=1}^n\sum_{j=1}^n \frac{i^2}{n^2}- \sum_{i=1}^n\sum_{j=1}^n \frac{j}{n}\right) \\
&= \frac{16}{n^2} \left(3n^2 - \sum_{i=1}^n n\frac{i^2}{n^2} - \sum_{j=1}^n n\frac{j}{n}\right) \\
&= \frac{16}{n^2} \left(3n^2 - \frac{1}{n}\sum_{i=1}^n i^2 - \sum_{j=1}^n j\right) \\
&= \frac{16}{n^2} \left(3n^2 - \frac{1}{n}\frac{n(n+1)(2n+1)}{6} - \frac{n(n+1)}{2}\right) \\
&= 48 - 16\frac{2n^2+3n+1}{6n^2} - 16\frac{n(n+1)}{2n^2} \\
&= 48 - \frac{16}{6}\left(2 +\frac{3}{n}+\frac{1}{n^2}\right) - 8\left(1+\frac{1}{n}\right) \\
&= \frac{104}{3} -\frac{16}{n} -\frac{16}{6n^2},
\end{align*}

y la integral inferior de Riemann es

$$
\lim_{n\to\infty} s(f,P)
= \lim_{n\to\infty} \frac{104}{3} -\frac{16}{n} -\frac{16}{6n^2}
= \frac{104}{3}.
$$

Del mismo modo, tomando $f$ en los extremos inferiores de cada subintervalo, es decir, en el punto $(x_{i-1},y_{j-1})$, se puede calcular la suma superior de Riemann y la integral superior de Riemann vale lo mismo, por lo que la función es integrable Riemann en el intervalo $I=[0,2]\times[0,2]$, y la integral vale

$$
\int_I 12-x^2-2y\,dA = \frac{104}{3}.
$$
:::

:::{#exr-integrales-dobles}
Calcular las siguientes integrales dobles

a. $\int_I x\cos(xy)\,dA$, con $I=[0,\pi/2]\times[0,1]$.

a. $\int_I \frac{x^2y}{y^2+1}\,dA$, con $I=[-1,1]\times[0,2]$.

a. $\int_I \frac{\ln(y)}{xy}\,dA$, con $I=[1,e]\times[1,e]$.

a. $\int_I \frac{xy}{x^2+y^2}\,dA$, con $I=[0,1]]\times[0,1]$.
:::

:::{.callout-tip collapse="true"}
## Solución
a. 

    \begin{align*}
    \int_I x\cos(xy)\,dA
    &= \int_0^{\pi/2}\int_0^{1}x\cos(xy)\,dy\,dx
    = \int_0^{\pi/2}[\operatorname{sen}(xy)]_0^1\,dx \\
    &= \int_0^{\pi/2}\operatorname{sen}(x)\,dx 
    = [-\cos(x)]_0^{\pi/2}
    = 1.
    \end{align*}

a.  

    \begin{align*}
    \int_I \frac{x^2y}{y^2+1}\,dA
    &= \int_0^2\int_{-1}^1 \frac{x^2y}{y^2+1}\,dx\,dy
    = \int_0^2 \left[\frac{x^3y}{3(y^2+1)}\right]_{-1}^1,dy \\
    &= \int_0^2 \frac{2y}{3y^2+3},dy 
    = \left[\frac{\ln(y^2+1)}{3}\right]_0^2 
    = \frac{\ln(5)}{3}.
    \end{align*}

a.  

    \begin{align*}
    \int_I \frac{\ln(y)}{xy}\,dA
    &= \int_1^e\int_1^e \frac{\ln(y)}{xy}\,dx\,dy
    = \int_1^e \left[\frac{\ln(x)\ln(y)}{y}\right]_1^e,dy \\
    &= \int_0^e \frac{\ln(y)}{y},dy 
    = \left[\frac{1}{2}\ln(y)^2\right]_1^e 
    = \frac{1}{2}.
    \end{align*}

a.  

    \begin{align*}
    \int_I \frac{xy}{x^2+y^2}\,dA
    &= \int_0^1\int_0^1 \frac{xy}{x^2+y^2}\,dx\,dy
    = \int_1^1 \left[\frac{1}{2}y\ln(x^2+y^2)\right]_0^1\,dy \\
    &= \int_0^1 \frac{1}{2}(-y\ln(y^2)+y\ln(y^2+1))\,dy  \\
    &= \left[\frac{1}{4}(-y^2\ln(y^2)+y^2+y^2\ln(y^2+1)-y^2+\ln(y^2+1)) \right]_0^1 \\
    &= \frac{\ln(2)}{2}.
    \end{align*}
:::

:::{#exr-volumne-funcion-positiva-negativa}
Calcular el volumen de la región encerrada por la función $f(x,y)=x^3y$ en el intervalo $[-1,1]\times[-1,1]$.
:::

:::{.callout-tip collapse="true"}
## Solución
A la hora de calcular el volumen hay que tener en cuenta que la función $f(x,y)=x^3y$ es positiva para los puntos $(x,y)$ del primer y tercer cuadrantes, y negativa en el segundo y cuarto cuadrantes. Así pues, descompondremos el intervalo de integración en los cuatro subintervalos $[-1,0]\times[-1,0]$, $[-1,0]\times[0,1]$, $[0,1]\times[-1,0]$ y $[0,1]\times[0,1]$. Las integrales dobles en estos subinvervalos valen

\begin{align*}
\int_{-1}^0\int_{-1}^0 f(x,y)\,dx\,dy
& = \int_{-1}^0x^3\,dx \int_{-1}^0 y\,dy 
= \left[\frac{x^4}{4}\right]_{-1}^0 \left[\frac{y^2}{2}\right]_{-1}^0 \\
&= \frac{-1}{4}\frac{-1}{2}
= \frac{1}{8}.
\end{align*}

\begin{align*}
\int_{-1}^0\int_{0}^1 -f(x,y)\,dx\,dy
& = \int_{-1}^0 -x^3\,dx \int_{0}^1 y\,dy 
= \left[\frac{-x^4}{4}\right]_{-1}^0 \left[\frac{y^2}{2}\right]_{0}^1 \\
&= \frac{1}{4}\frac{1}{2}
= \frac{1}{8}.
\end{align*}

\begin{align*}
\int_{0}^1\int_{-1}^0 -f(x,y)\,dx\,dy
& = \int_{0}^1 x^3\,dx \int_{-1}^0 y\,dy 
= \left[\frac{-x^4}{4}\right]_{0}^1 \left[\frac{y^2}{2}\right]_{-1}^0 \\
&= \frac{-1}{4}\frac{-1}{2}
= \frac{1}{8}.
\end{align*}

\begin{align*}
\int_{0}^1\int_{0}^1 f(x,y)\,dx\,dy
& = \int_{0}^1 x^3\,dx \int_{0}^1 y\,dy 
= \left[\frac{x^4}{4}\right]_{0}^1 \left[\frac{y^2}{2}\right]_{0}^1 \\
&= \frac{1}{4}\frac{1}{2}
= \frac{1}{8}.
\end{align*}

Por tanto, el volumen total será la suma de los volúmenes correspondientes a los subintervalos, es decir $\frac{1}{8} + \frac{1}{8} + \frac{1}{8} + \frac{1}{8} = \frac{1}{2}$.
:::

:::{#exr-integrales-dobles-regiones-irregulares}
Calcular las siguientes integrales dobles sobre las regiones irregulares dadas.

a.  $\int_R \frac{y}{x}\,dA$, con $R=\left\{(x,y)\in\mathbb{R}^2: 0\leq x\leq 2, 0\leq y\leq x^2\right\}$

a.  $\int_R xy^2\,dA$, con $R=\{(x,y)\in\mathbb{R}^2: 0\leq x\leq \sqrt{1-y^2}, -1\leq y\leq 1\}$.

a.  $\int_R \operatorname {sen}{y^2}\,dA$, con $R=\{(x,y)\in\mathbb{R}^2: 0\leq x\leq \sqrt{\pi}, x\leq y\leq \sqrt{\pi}\}$.

a.  $\int_R e^{-x^2}\,dA$, con $R=\{(x,y)\in\mathbb{R}^2: y\leq x\leq 1, 0\leq y\leq 1\}$.

:::

:::{.callout-tip collapse="true"}
## Solución
a.  

    \begin{align*}
    \int_R \frac{y}{x}\,dA 
    &= \int_0^2 \int_0^{x^2} \frac{y}{x}\,dy\,dx
    = \int_0^2 \left[\frac{y^2}{2x}\right]_0^{x^2} \\
    &= \int_0^2 \frac{x^3}{2}\,dx
    = \left[\frac{x^4}{8}\right]_0^2
    = 2.
    \end{align*}

a.  

    \begin{align*}
    \int_R xy^2\,dA 
    &= \int_{-1}^1 \int_0^{\sqrt{1-y^2}} xy^2\,dx\,dy
    = \int_{-1}^1 \left[\frac{x^2}{2}y^2\right]_0^{\sqrt{1-y^2}} \,dy \\
    &= \int_{-1}^1 \frac{1}{2}(1-y^2)y^2\,dy 
    = \frac{1}{2}\left[\left(\frac{y^3}{3}-\frac{y^5}{5}\right)\right]_{-1}^1 \\
    &= \frac{1}{2}\left(\frac{2}{3}-\frac{2}{5}\right)
    = \frac{2}{15}.
    \end{align*}

a.  

    \begin{align*}
    \int_R \operatorname{sen}(y^2)\,dA  
    &= \int_0^{\sqrt{\pi}} \int_x^{\sqrt{\pi}} \operatorname{sen}(y^2)\,dy\,dx 
    = \int_0^{\sqrt{\pi}}\int_0^y \operatorname{sen}(y^2)\,dx\,dy \\
    &= \int_0^{\sqrt{\pi}} [x\operatorname{sen}(y^2)]_0^y\,dy 
    = \int_0^{\sqrt{\pi}} y\operatorname{sen}(y^2)\,dy \\
    &= \left[-\frac{1}{2}\cos(y^2)\right]_0^{\sqrt{\pi}} 
    = -\frac{1}{2}(-1-1)
    = 1.
    \end{align*}

a.  

    \begin{align*}
    \int_R e^{-x^2}\,dA  
    &= \int_0^1 \int_y^1 e^{-x^2}\,dx\,dy 
    = \int_0^1\int_0^x e^{-x^2}\,dy\,dx \\
    &= \int_0^1 [ye^{-x^2}]_0^x\,dx 
    = \int_0^1 xe^{-x^2}\,dx \\
    &= \left[-\frac{1}{2}e^{-x^2}\right]_0^1
    = -\frac{1}{2}\left(\frac{1}{e}-1\right)
    = \frac{e-1}{2e}.
    \end{align*}
:::

:::{#exr-volumen-piramide}
Calcular el volumen de una pirámide de base cuadrada con lado $l$ centrada en el origen de coordenadas y altura $h$, usando una integral doble. ¿Cuál es la altura media de la pirámide?
:::

:::{.callout-tip collapse="true"}
## Solución
Por simetría, podemos reducir el problema a calcular el volumen que queda por debajo de cada una de las caras de la pirámide. 

Si nos fijamos en la cara que cae el semiplano con $x$ positiva, tenemos que la ecuación del plano que contiene esa cara es $f(x,y) = h\left(1 - \frac{2x}{a}\right)$, por lo que para obtener el volumen por debajo de esta cara hay que integrar esta función en el intervalo $I=[0, a/2]\times[-x,x]$.

\begin{align*}
\int_I f(x,y) \,dA 
&= \int_0^{a/2} \int_{-x}^x h\left(1 - \frac{2x}{a}\right)\,dy\,dx 
= \int_0^{a/2} \left[h\left(1 - \frac{2x}{a}\right)y\right]_{-x}^x\,dx \\
&= \int_0^{a/2} h\left(1 - \frac{2x}{a}\right)2x\,dx 
= \int_0^{a/2} h\left(2x - \frac{4x^2}{a}\right)\,dx \\
&= h\left[x^2-\frac{4x^3}{3a}\right]_0^{a/2}
= h(\left(\frac{a^2}{4}-\frac{a^2}{6}\right) 
= \frac{ha^2}{12}.
\end{align*}

Así pues, el volumen total de la pirámide será 4 veces esta cantidad, ya que la pirámide tiene 4 caras, es decir, $4\frac{ha^2}{12} = \frac{1}{3}a^2h$, que coincide con la fórmula habitual para calcular el volumen de una pirámide de base cuadrada.
:::

:::{#exr-volumen-piscina}
Una piscina con forma elíptica de ecuación $x^2+2y^2 = 16$ tiene una profundidad de 1 m en el extremo izquierdo y de 2 m en el extremo derecho, y su profundidad crece de izquierda a derecha de forma constante. Calcular la cantidad de agua que hay en la piscina.
:::

:::{.callout-tip collapse="true"}
## Solución
La ecuación $x^2+2y^2=16$ define una elipse centrada en el origen de coordenadas y cuyos extremos en el eje $x$ están en $x=-4$ y $x=4$, por lo que la región que define la elipse en el plano $xy$ es 

$$
R = \left\{(x,y)\in\mathbb{R}^2: -4\leq x\leq 4, -\sqrt{\frac{16-x^2}{2}}\leq y\leq \sqrt{\frac{16-x^2}{2}}\right\},
$$

o bien

$$
R = \{(x,y)\in\mathbb{R}^2: -\sqrt{8}\leq y\leq \sqrt{8}, -\sqrt{16-2y^2}\leq x\leq \sqrt{16-2y^2}\}.
$$

Supongamos que el plano $xy$ es el nivel del agua. Entonces el fondo de la piscina estará contenido en el plano paralelo al eje $y$ que contenga los puntos $(-4,-1)$, $(4,-2)$, que tiene ecuación $f(x,y) = -1-\frac{1}{8}(x+4) = -\frac{3}{2}-\frac{x}{8}$. Por tanto se trata de calcular el volumen encerrado entre este plano y el plano $xy$ en la región $R$, que viene dado por la integral doble

\begin{align*}
\int_R -f(x,y)\,dA
&= \int_{-\sqrt{8}}^{\sqrt{8}} \int_{-\sqrt{16-2y^2}}^{\sqrt{16-2y^2}} \frac{3}{2}+\frac{x}{8}\,dx\,dy \\
&= \int_{-\sqrt{8}}^{\sqrt{8}} \left[\frac{3x}{2}-\frac{x^2}{16}\right]_{-\sqrt{16-2y^2}}^{\sqrt{16-2y^2}}\,dy \\
&= \int_{-\sqrt{8}}^{\sqrt{8}} \left(\frac{3}{2}(\sqrt{16-2y^2}+ \sqrt{16-2y^2})\right. \\
&+ \left.\frac{1}{16}((\sqrt{16-2y^2})^2-(-\sqrt{16-2y^2})^2)\right)\,dy \\
&= \int_{-\sqrt{8}}^{\sqrt{8}} 3\sqrt{16-2y^2} \,dy 
= 3\int_{\pi}^0 \frac{-16}{\sqrt{2}}\operatorname{sen}(\theta)^2\,d\theta \tag{1} \\
&= \frac{-48}{\sqrt{2}}\int_{\pi}^0 \frac{1-\cos(2\theta)}{2}\,d\theta 
= \frac{-24}{\sqrt{2}} \left[\theta-\frac{\operatorname{sen}(2\theta)}{2}\right]_{\pi}^0 \\
&= \frac{-24}{\sqrt{2}} \left(0-\frac{\operatorname{sen}(2\cdot 0)}{2}-\pi+\frac{\operatorname{sen}(2\pi)}{2}\right)
= 12\sqrt{2}\pi.
\end{align*}
(1) Cambio de variable $\sqrt{2}y=4\cos(\theta)$.

Así pues, la piscina tiene $12\sqrt{2}\pi\approx 53.3146$ m$^3$ de agua.
:::

:::{#exr-volumen-entre-dos-superficies}
Calcular el volumen encerrado por las superficies $z=1-x^2-y^2$ y $z=1-x$.
:::

:::{.callout-tip collapse="true"}
## Solución
Sea $f(x,y)=1-x^2-y^2$ y $g(x,y)=1-x$. Veamos primero en qué región se cortan las dos superficies. 

$$
1-x^2-y^2 = 1 -x \Leftrightarrow y^2 = -x^2+x \Leftrightarrow y=\pm\sqrt{-x^2+x},
$$

por lo que la región sobre la que se cortan las dos gráficas es $R=\{(x,y)\in\mathbb{R}^2: 0\leq x\leq 1, -\sqrt{-x^2+x}\leq y\leq \sqrt{x^2+x}\}$, que es la circunferencia de radio $1/2$ centrada en el punto $(0.5,0)$.

En este caso resulta más sencillo, trabajar en coordenadas polares. Si resolvemos la ecuación anterior en coordenadas polares, se tiene

$$
\begin{gathered}
1-(r\cos(\theta))^2-(r\operatorname{sen}(\theta))^2 = 1-r\cos(\theta)
\Leftrightarrow 1-r^2 = 1-r\cos(\theta) \\
\Leftrightarrow r^2 = r\cos(\theta)
\Leftrightarrow r=0 \mbox{ o } r=\cos(\theta),
\end{gathered}
$$

por lo que la región de integración en coordenadas polares es $R=\{(r,\theta)\in \mathbb{R}^+\times \mathbb{R}: -\pi/2\leq \theta\leq \pi/2, 0\leq r\leq \cos(\theta)\}$, y la integral que da el volumen comprendido entre las dos superficies es

\begin{align*}
\int_{R} f(x,y)-g(x,y)\,dA
&= \int_{-\pi/2}^{\pi/2} \int_0^{\cos(\theta)} (1-r^2 - (1-r\cos(\theta)))r\,dr\,d\theta \\
&= \int_{-\pi/2}^{\pi/2} \int_0^{\cos(\theta)} -r^3+r^2\cos(\theta))\,dr\,d\theta \\
&= \int_{-\pi/2}^{\pi/2} \left[-\frac{r^4}{4}+\frac{r^3}{3}\cos(\theta)\right]_0^{\cos(\theta)} \,d\theta \\
&= \int_{-\pi/2}^{\pi/2} \frac{-\cos(\theta)^4}{4}+\frac{\cos(\theta)^3}{3}\cos(\theta) \,d\theta \\
&= \int_{-\pi/2}^{\pi/2} \frac{1}{12}\cos(\theta)^4 \,d\theta \\
&= \frac{1}{12}\int_{-\pi/2}^{\pi/2} \left(\frac{1+\cos(2\theta)}{2}\right)^2 \,d\theta \\
&= \frac{1}{48}\int_{-\pi/2}^{\pi/2} 1+2\cos(2\theta)+\cos(2\theta)^2\,d\theta \\
&= \frac{1}{48}\int_{-\pi/2}^{\pi/2} 1+2\cos(2\theta)+\frac{1+\cos(4\theta)}{2}\,d\theta \\
&= \frac{1}{48}\left[\theta+\operatorname{sen}(2\theta)+\frac{\theta}{2}+\frac{\operatorname{sen}(4\theta)}{8}\right]_{-\pi/2}^{\pi/2} \\
&= \frac{1}{48}\left(\frac{\pi}{2}+\operatorname{sen}(2\pi/2)+\frac{\pi/2}{2}+\frac{\operatorname{sen}(4\pi/2)}{8}\right. \\
&\left.- \frac{-\pi}{2} - \operatorname{sen}(-2\pi/2)-\frac{-\pi/2}{2}-\frac{\operatorname{sen}(-4\pi/2)}{8}\right) \\
&= \frac{\pi}{32}.
\end{align*}
:::

:::{#exr-integral-polar-petalo}
Un escudo contiene una flor dada por la función $r(\theta) = \cos(2\theta)$. Calcular la cantidad de tela necesaria (en metros) para construir la flor del escudo.
:::

:::{.callout-tip collapse="true"}
## Solución
La región de integración es $R=\{(r,\theta)\in \mathbb{R}^+\times\mathbb{R}: 0\leq \theta\leq 2\pi, 0\leq r\leq \cos(2\theta)\}$, y como queremos calcular el area de esta región, basta con integrar la función $f(r,\theta)=1$ sobre la región de integración en coordenadas polares, es decir,

\begin{align*}
\int_0^{2\pi} \int_0^{\cos(2\theta)} r\,dr\,d\theta
&= \int_0^{2\pi} \left[\frac{r^2}{2}\right]_0^{\cos(2\theta)} \,d\theta
= \int_0^{2\pi} \frac{1}{2}\cos(2\theta)^2 \,d\theta \\
&= \frac{1}{2}\int_0^{2\pi} \frac{1+\cos(4\theta)}{2} \,d\theta 
= \frac{1}{4} \left[\theta + \frac{\operatorname{sen}(4\theta)}{4}\right]_0^{2\pi}\\
&= \frac{1}{4}\left(2\pi + \frac{\operatorname{sen}(8\pi)}{4}-0-\frac{\operatorname{sen}(0)}{4}\right)
=\pi/2.
\end{align*}

Así pues, se necesitarán $\pi/2\approx 1.5708$ m$^2$ de tela.
:::

:::{#exr-integral-doble-area-superficies}
Calcular el area de las superficies de las siguientes funciones en las regiones indicadas.

a.  $f(x,y)=xy$, en $R=\{(x,y)\in \mathbb{R}^2: x^2+y^2\leq 1\}$.
a.  $g(x,y)=\ln(\sec(x))$, en $R=\{(x,y)\in \mathbb{R}^2: 0\leq x\leq \pi/4, 0\leq y\leq \operatorname{tg}(x)\}$.
:::

:::{.callout-tip collapse="true"}
## Solución
a.  Calculamos primero las derivadas parciales de $f$.

    \begin{align*}
    f'_x(x,y) &= y,\\
    f'_y(x,y) &= x.
    \end{align*}

    Por tanto, la integral que da la superficie es

    $$
    \int_R \sqrt{f'_x(x,y)^2+f'_y(x,y)^2+1}\,dA
    = \int_{-1}^1 \int_{-\sqrt{1-x^2}}^{\sqrt{1-x^2}} \sqrt{y^2+x^2+1}\,dy\,dx.
    $$

    Esta integral resulta más sencilla si hacemos el cambio a coordenadas polares.

    \begin{align*}
    \int_R \sqrt{f'_x(x,y)^2+f'_y(x,y)^2+1}\,dA
    &= \int_0^{2\pi} \int_0^1 \sqrt{(r\cos(\theta))^2+(r\operatorname{sen}(\theta))^2+1}r\,dr\,d\theta \\
    &= \int_0^{2\pi} \int_0^1 \sqrt{r^2+1}r\,dr\,d\theta \\
    &= \frac{1}{2} \int_0^{2\pi} \left[\frac{(r^2+1)^{3/2}}{3/2}\right]_0^1\,d\theta \\
    &= \frac{1}{3} \int_0^{2\pi} (1^2+1)^{3/2}-(0^2+1)^{3/2}\,d\theta \\
    &= \frac{1}{3} \int_0^{2\pi} (\sqrt{8}-1)\,d\theta \\
    &= \frac{\sqrt{8}-1}{3} [\theta]_0^{2\pi} 
    = \frac{\sqrt{8}-1}{3}2\pi.
    \end{align*}

a.  Calculamos primero las derivadas parciales de $f$.

    \begin{align*}
    f'_x(x,y) &= \frac{1}{\sec(x)}\sec(x)\operatorname{tg}(x) = \operatorname{tg}(x),\\
    f'_y(x,y) &= 0.
    \end{align*}

    Por tanto, la integral que da la superficie es

    \begin{align*}
    \int_R \sqrt{f'_x(x,y)^2+f'_y(x,y)^2+1}\,dA
    &= \int_{0}^{\pi/4} \int_{0}^{\operatorname{tg}(x)} \sqrt{\operatorname{tg}(x)^2+1}\,dy\,dx \\
    &= \int_{0}^{\pi/4} \sqrt{\operatorname{tg}(x)^2+1}[y]_0^{\operatorname{tg}(x)}\,dx \\
    &= \int_{0}^{\pi/4} \sqrt{\operatorname{tg}(x)^2+1}\operatorname{tg}(x)\,dx \\
    &= \int_1^2 \frac{u^{-1/2}}{2}\,du \tag{1}\\
    &= [\sqrt{u}]_1^2 
    = \sqrt{2}-1.
    \end{align*}
    (1) Cambio $u=\operatorname{tg}(x)^2+1$.
:::

:::{#exr-area-superficie-chimenea}
Una tolva tiene forma cónica dada por la función $f(x,y)=2\sqrt{x^2+y^2}$ con altura 4 m. Calcular el volumen de la tolva y la cantidad de chapa necesaria para construirla.
:::

:::{.callout-tip collapse="true"}
## Solución
Para obtener el volumen de la tolva necesitamos calcular el volumen comprendido entre el plano $z=4$ a nivel de la altura de la tolva y la superficie cónica de $f$ en la región en la región de intersección del plano con superficie cónica, es decir, $2\sqrt{x^2+y^2} = 4 \Leftrightarrow x^2+y^2 = 4$, que se trata del círculo centrado en el origen con radio $2$. Por tanto, la región de integración es $R=\{(x,y)\in\mathbb{R}^2: -2\leq x\leq 2, -\sqrt{4-x^2}\leq y\leq \sqrt{4-x^2}\}$. 

Por la forma de $f$ y de la región de integración, en este caso, resulta más sencillo trabajar en coordenadas polares, ya que la región de integración se convierte en $R=\{(r,\theta)\in \mathbb{R}^+\times\mathbb{R}: 0\leq \theta 2\pi, 0\leq r\leq 2\}$, por lo que el volumen que buscamos es puede obtener mediante la integral

\begin{align*}
\int_R 4-f(x,y)\,dA 
&= \int_0^{2\pi}\int_0^2 (4-f(r\cos(\theta),r\operatorname{sen}{\theta}))r\,dr\,d\theta \\
&= \int_0^{2\pi}\int_0^2 4r-2r^2\,dr\,d\theta 
= \int_0^{2\pi} \left[2r^2-\frac{2r^3}{3}\right]_0^2\,d\theta \\
&= \int_0^{2\pi} 8-\frac{16}{3}\,d\theta 
= \frac{8}{3} [\theta]_0^{2\pi} 
= \frac{16}{3}\pi \mbox{ m}^3.
\end{align*}

Para obtener su superficie necesitamos calcular la integral $\int_R \sqrt{f'_x(x,y)^2+f'_y(x,y)^2+1}\,dA$, por lo que primero debemos calcular las derivadas parciales de $f$, que son

\begin{align*}
f'_x(x,y) &= \frac{2x}{\sqrt{x^2+y^2}} \\
f'_x(x,y) &= \frac{2x}{\sqrt{x^2+y^2}}, 
\end{align*}

por lo que la función a integrar es 

$$
\sqrt{f'_x(x,y)^2+f'_y(x,y)^2+1} 
= \sqrt{\frac{4x^2}{x^2+y^2}+\frac{4y^2}{x^2+y^2}+1} 
= \sqrt{5}.
$$

Al igual que antes, resulta más sencillo trabajar en coordenadas polares, por lo que la superficie de la tolva viene dada por la integral

\begin{align*}
\int_R \sqrt{f'_x(x,y)^2+f'_y(x,y)^2+1}\,dA
&= \int_{0}^{2\pi} \int_0^2 \sqrt{5}r \,dr\,d\theta 
= \int_{0}^{2\pi} \sqrt{5}\left[\frac{r^2}{2}\right]_0^2\,d\theta \\
&= \int_{0}^{2\pi} 2\sqrt{5}\,d\theta 
= [2\sqrt{5}\theta]_0^{2\pi}
= 4\sqrt{5}\pi \mbox{ m}^2. 
\end{align*}
:::

:::{#exr-integral-doble-valor-medio}
Calcular el valor medio de la función $f(x,y)=\sqrt{xy}$ en la región del primer cuadrante delimitada por las funciones $y=x$ e $y=x^2$.
:::

:::{.callout-tip collapse="true"}
## Solución
Como las funciones $y=x$ e $y=x^2$ se cortan en los puntos $(0,0)$ y $(1,1)$, la región de integración es $R=\{(x,y)\in\mathbb{R}^2: 0\leq x\leq 1, x^2\leq y \leq x\}$. 
El valor medio de la función en esta región es el valor de la integral doble de $f$ sobre la región, dividida por el área de la región. 

Calculamos primero la integral doble de $f$ sobre $R$.

\begin{align*}
\int_R f(x,y)\,dA 
&= \int_0^1\int_{x^2}^x \sqrt{xy}\,dy\,dx
= \int_0^1 \left[\frac{(xy)^{3/2}}{\frac{3}{2}x}\right]_{x^2}^x\,dx \\
&= \int_0^1 \frac{2 (x^2)^{3/2}}{3x}- \frac{2(x^3)^{3/2}}{3x}
= \left[\frac{2(x^2)^{3/2}}{9} - \frac{4(x^3)^{3/2}}{27} \right]_0^1
= \frac{2}{27}.
\end{align*}

Y ahora calculamos el area de la región $R$.

$$
\int_0^1 x-x^2\,dx 
= \left[\frac{x^2}{2}-\frac{x^3}{3}\right]_0^1
= \frac{1}{2}-\frac{1}{3}
= \frac{1}{6}.
$$

Por lo tanto, el valor medio de $f$ en la región $R$ es $\frac{2/27}{1/6} = \frac{12}{27}$.
:::

:::{#exr-masa-lamina-chapa}
Una lámina de chapa metálica tiene la forma de la forma de triángulo con vértices $(0,0)$, $(1,1)$ y $(2,0)$. Si la densidad de la chapa en cada punto viene dada por la función $d(x,y)=e^{x+y}$ gr/cm$^2$, calcular la masa de la chapa y su centro de masas.
:::

:::{.callout-tip collapse="true"}
## Solución
El triángulo está delimitado por las rectas $y=0$, $y=x$ e $y=2-x$, por lo que la región de integración puede expresarse como $R=\{(x,y)\in\mathbb{R}^: 0\leq y\leq 1, y\leq x\leq 2-y\}$. Para obtener la masa de la placa basta con integrar la función de densidad en esta región.

\begin{align*}
m
&= \int_R d(x,y)\,dA
= \int_0^1 \int_y^{2-y} e^{x+y}\,dx\,dy
= \int_0^1 [e^{x+y}]_y^{2-y} \,dy \\
&= \int_0^1 e^2 - e^{2y} \,dy 
= \left[e^2 y- \frac{e^{2y}}{2}\right]_0^1
= e^2 - \frac{e^2}{2} - 0 + \frac{1}{2}
= \frac{e^2+1}{2} \mbox{ gr}.
\end{align*}

Para calcular el centro de masas de la placa, primero tenemos que calcular los momentos de masas con respecto a $x$ e $y$.

\begin{align*}
M_x
&= \int_R yd(x,y)\,dA
= \int_0^1 \int_y^{2-y} ye^{x+y}\,dx\,dy
= \int_0^1 [ye^{x+y}]_y^{2-y} \,dy \\
&= \int_0^1 y(e^2 - e^{2y}) \,dy
= \int_0^1 ye^2-ye^{2y}\,dy 
= e^2\left[e^2\frac{y^2}{2}-\frac{(2y-1)e^{2y}}{4} \right]_0^1 \\
&= \frac{e^2}{2} - \frac{e^2}{4} - \frac{1}{4}
= \frac{e^2-1}{4}\mbox{cm$\cdot$gr}. \\
M_y
&= \int_R xd(x,y)\,dA
= \int_0^1 \int_y^{2-y} xe^{x+y}\,dx\,dy
= \int_0^1 [(x-1)e^{x+y}]_y^{2-y} \,dy \\
&= \int_0^1 (1-y)e^2-(y-1)e^{2y} \,dy
= \left[\left(y-\frac{y^2}{2}\right)e^2 - \frac{(2y-3)e^{2y}}{4}\right]_0^1 \\
&= \left(1-\frac{1}{2}\right)e^2 + \frac{e^2}{4} - \frac{3}{4}
= \frac{3e^2-3}{4}\mbox{cm$\cdot$gr}.
\end{align*}

Así pues, el centro de masas de la placa tiene las siguientes coordenadas

\begin{align*}
\bar x 
&= \frac{M_y}{m} 
= \frac{\frac{3e^2-3}{4}}{\frac{e^2+1}{2}}
= \frac{3e^2-3}{2(e^2+1)} 
\approx 1.1424 \mbox{cm}\\
\bar y
&= \frac{M_x}{m} 
= \frac{\frac{e^2-1}{4}}{\frac{e^2+1}{2}}
= \frac{e^2-1}{2(e^2+1)} 
\approx 0.3808 \mbox{cm}
\end{align*}
:::

:::{#exr-presion-ala-avión}
El perfil de la sección transversal del ala de un avión viene dada por las curvas $y=\frac{(-1+x^2)}{10}$ e $y=\frac{1-x^2}{10}$ en metros. Calcular el área de la superficie de un ala de 10 m de longitud.  
:::

:::{.callout-tip collapse="true"}
## Solución
Para ver dónde se cortan las dos curvas resolvemos la ecuación que resulta de igualarlas.

$$
\frac{(-1+x^2)}{10} = \frac{1-x^2}{10} \Leftrightarrow 2x^2 - 2 = 0 \Leftrightarrow x=-1 \mbox{ o } x=1.
$$

Así pues, la región de integración es $R=\{(x,y)\in \mathbb{R}^2: -1\leq x\leq 1, 0\leq y\leq 10\}$.

Por simetría, la superficie de la parte superior del ala tiene el mismo area que la superficie de la parte inferior, por lo que basta con calcular el area de la superficie de la parte superior, que se corresponde con la función $f(x,y)=\frac{1}{10}(x^2-1)$, y su area se obtiene con la integral 

\begin{align*}
\int_R \sqrt{f'_x(x,y)^2+f'_y(x,y)^2+1}\,dA
&= \int_{-1}^1\int_0^10 \sqrt{\left(\frac{2x}{10}\right)^2+1}\,dy\,dx \\
&= \int_{-1}^1\int_0^10 \sqrt{\frac{x^2+25}{25}}\,dy\,dx \\
&= \int_{-1}^1 \sqrt{\frac{x^2+25}{25}} [y]_0^10\,dx \\
&= \int_{-1}^1 10 \sqrt{\frac{x^2+25}{25}} \,dx \\
&= 2\int_{-1}^1 \sqrt{x^2+25} \,dx \\
&= 2\int_{\operatorname{arctg}(-1/5)}^{\operatorname{arctg}(1/5)} \sqrt{(5\operatorname{tg}(\theta))^2+25} 5\sec(\theta)^2\,d\theta \tag{1}\\
&= 10\int_{\operatorname{arctg}(-1/5)}^{\operatorname{arctg}(1/5)} 5\sqrt{\operatorname{tg}(\theta)^2+1}\sec(\theta)^2\,d\theta \\
&= 50\int_{\operatorname{arctg}(-1/5)}^{\operatorname{arctg}(1/5)} \sec(\theta)^3\,d\theta \tag{2} \\
&= 50\left[ \frac{1}{2}\sec(\theta)\operatorname{tg}(\theta) + \frac{1}{2} \ln|\sec(\theta)+\operatorname{tg}(\theta)|\right]_{\operatorname{arctg}(-1/5)}^{\operatorname{arctg}(1/5)}\,d\theta \\
&= 20.1325 \mbox{ m}^2.
\end{align*}
(1) Sustitución trigonométrica $x= 5\operatorname{tg}(\theta)$.  
(2) $\int \sec(\theta)^3\,d\theta = \frac{1}{2}\sec(\theta)\operatorname{tg}(\theta) + \frac{1}{2} \ln|\sec(\theta)+\operatorname{tg}(\theta)|$ por partes.

Por tanto, el area de la superficie del ala es $40.265$ m$^2$.
:::

:::{#exr-funcion-densidad-exponencial-exponencial}
La función de densidad de probabilidad de una variable aleatoria bidimensional es

$$
f(x,y) = 
\begin{cases}
ke^{-(x+y)/2} & x\geq 0, y\geq 0\\
0 & \mbox{en caso contrario}
\end{cases}
$$

a.  ¿Qué valor debe tener $k$ para que $f$ sea una función de densidad?

b.  Calcular la media de la variable bidimensional.
:::

:::{.callout-tip collapse="true"}
## Solución
a.  Para que $f$ sea una función de densidad de probabilidad el volumen total encerrado entre la superficie de $f$ y el plano $z=0$ debe ser $1$. Este volumen viene dado por la integral doble impropia 

    \begin{align*}
    \int_0^\infty \int_0^\infty f(x,y)\,dx\,dy
    &= \int_0^\infty \int_0^\infty ke^{-(x+y)/2}\,dx\,dy 
    = \int_0^\infty \left[-2ke^{-(x+y)/2}\right]_0^\infty\,dy \\
    &= \int_0^\infty 2ke^{-y/2}\,dy 
    = [-4ke^{-y/2}]_0^\infty 
    = 4k,
    \end{align*}

    por lo que para que $f$ sea función de densidad, debe ser $k=1/4$.

a.  Las componentes $x$ de la media muestral de la variable viene dada por la integral dobles impropia

    \begin{align*}
    \bar x 
    = \int_0^\infty \int_0^\infty xf(x,y)\,dx\,dy
    &= \int_0^\infty \int_0^\infty \frac{1}{4}xe^{-(x+y)/2}\,dx\,dy 
    = \frac{1}{4}\int_0^\infty \left[(-2x-4)e^{-(x+y)/2}\right]_0^\infty\,dy \\
    &= \frac{1}{4}\int_0^\infty 4e^{-y/2}\,dy 
    = [-2e^{-y/2}]_0^\infty 
    = 2.
    \end{align*}

    Y por simetría, la componente $y$ vale lo mismo por lo que la media muestral es $(2,2)$.
:::

