---
lang: es
---
<!-- LTeX: language = es-ES -->

# Límites de funciones

:::{#exr-funcion-constante}
Sea $f(x)=c$ una función constante. Demostrar que $\lim_{x\to a}f(x)=c$ $\forall a\in\mathbb{R}$.  
:::

:::{.callout-tip collapse="true"}
## Solución
Para cualquier $\varepsilon>0$ se puede tomar $\delta = 1$ tal que si $|x-a|<\delta=1$, entonces $|f(x)-c| = |c-c|=0<\varepsilon$.
:::

:::{#exr-definicion-limite}
$\star$
Dada la función $f(x)=4x-10$, demostrar usando la definición de límite que $\lim_{x\to 3}f(x)=2$.  
:::

:::{.callout-tip collapse="true"}
## Solución
Para cualquier $\varepsilon>0$ se puede tomar $\delta = \frac{\varepsilon}{4}$ tal que si $|x-3|<\delta=\frac{\varepsilon}{4}$, entonces 

$$
|f(x)-2| = |4x-10-2|= |4x-12| = 4|x-3|<4\frac{\varepsilon}{4} =\varepsilon.
$$
:::

:::{#exr-limite-criterio-sucesiones}
$\star$
Dada la función $f(x)=\frac{|x|}{x}$, usar el criterio de las sucesiones para demostrar que no existe el límite de $f$ en $0$. 
:::

:::{.callout-tip collapse="true"}
## Solución
Tomando las sucesión $\left(\frac{-1}{n}\right)_{n=1}^\infty$ que converge a $0$, se tiene 

$$
\lim_{n\to\infty}f\left(\frac{-1}{n}\right)=\lim_{n\to\infty}\frac{|-1/n|}{-1/n} = -1.
$$

Y tomando la sucesión $\left(\frac{1}{n}\right)_{n=1}^\infty$ que también converge a $0$, se tiene

$$
\lim_{n\to\infty}f\left(\frac{1}{n}\right)=\lim_{n\to\infty}\frac{|1/n|}{1/n} = 1.
$$

Por tanto, por el criterio de las sucesiones convergentes, no existe el límite de $f$ en $0$.
:::

:::{#exr-limite-funcion-Dirichlet}
La función $f:\mathbb{R}\to \mathbb{R}$ dada por

$$
f(x)=\begin{cases}
1, & \mbox{si } x\in\mathbb{Q},\\ 
0, & \mbox{si } x\not\in \mathbb{Q}
\end{cases}
$$
se conoce como la _función de Dirichlet_. Demostrar que no existe el límite de $f$ en cualquier número real.
:::

:::{#exr-limite-coseno}
$\star$
Demostrar que no existe $\lim_{x\to 0}\cos\left(\frac{1}{x}\right)$.
:::

:::{#exr-limite-polinomios}
Dado un polinomio $p(x)$, demostrar que $\lim_{x\to a}p(x)=p(a)$ $\forall a\in\mathbb{R}$.
:::

:::{#exr-limite-funciones-racionales}
Dada una función racional $f(x)=\frac{p(x)}{q(x)}$ $\forall x\in\mathbb{R}$ tal que $q(x)\neq 0$, demostrar que $\lim_{x\to a}f(x)=f(a)$ $\forall a\in\mathbb{R}$ tal que $q(a)\neq 0$.
:::

:::{#exr-limite-emparedado}
$\star$
Demostrar, haciendo uso del [teorema de compresión de funciones](https://aprendeconalf.es/analisis-manual/limites.html#thm-compresión-funciones) que $\lim_{x\to 0}\frac{1-\cos(x)}{x} = 0$.
:::

:::{.callout-tip collapse="true"}
## Solución
\begin{align*}
\lim_{x\to 0}\frac{1-\cos(x)}{x} &= \lim_{x\to 0}\frac{(1-\cos(x))(1+\cos(x))}{x(1+\cos(x))} =  \lim_{x\to 0}\frac{1-\cos(x)^2}{x(1+\cos(x))}\\ 
&= \lim_{x\to 0}\frac{\operatorname{sen}(x)^2}{x(1+\cos(x))} = \lim_{x\to 0}\frac{\operatorname{sen}(x)}{x}\frac{\operatorname{sen}(x)}{1+\cos(x)} =\\ 
&= \lim_{x\to 0}\frac{\operatorname{sen}(x)}{x}\lim_{x\to 0}\frac{\operatorname{sen}(x)}{1+\cos(x)} =1\cdot 0 = 0.
\end{align*}
:::

:::{#exr-limites-1}
$\star$
Calcular los siguientes límites si existen:

:::: {.columns}
::: {.column}
a. $\displaystyle \lim_{x\to 2} \dfrac{x^2+x-6}{x-2}$

a. $\displaystyle \lim_{x\to 1}\dfrac{x^3-3x+2}{x^4-4x+3}$

a. $\displaystyle \lim_{x\to 0}\dfrac{\operatorname{sen}(x+a)-\operatorname{sen}(a)}{x}$

a. $\displaystyle \lim_{x\to\infty}\dfrac{x^2-3x+2}{e^{2x}}$

a. $\displaystyle \lim_{x\to\infty}\dfrac{\log(x^2-1)}{x+2}$

a. $\displaystyle \lim_{x\to 1}\dfrac{\log(1/x)}{\operatorname{tg}(x+\dfrac{\pi}{2})}$

a. $\displaystyle \lim_{x\to a}\dfrac{x^n-a^n}{x-a}\quad n\in \mathbb{N}$

a. $\displaystyle \lim_{x\to 1}\dfrac{\sqrt[n]{x}-1}{\sqrt[m]{x}-1} \quad n,m \in \mathbb{Z}$

a. $\displaystyle \lim_{x\to 0}\dfrac{\operatorname{tg}(x)-\operatorname{sen}(x)}{x^3}$
:::

::: {.column}
j. $\displaystyle \lim_{x\to \pi/4}\dfrac{\operatorname{sen}(x)-\cos(x)}{1-\operatorname{tg}(x)}$

a. $\displaystyle \lim_{x\to 0}x^2e^{1/x^2}$

a. $\displaystyle \lim_{x\to 0}\left(1+x\right)^{1/x}$

a. $\displaystyle \lim_{x\to \infty} \sqrt[x]{x^2}$

a. $\displaystyle \lim_{x\to 0}\left(\dfrac{1}{x}\right)^{\operatorname{tg}(x)}$

a. $\displaystyle \lim_{x\to 0}(\cos x)^{1/\operatorname{sen}(x)}$

a. $\displaystyle \lim_{x\to 0}\dfrac{6}{4+e^{-1/x}}$

a. $\displaystyle \lim_{x\to \infty}\left(\sqrt{x^2+x+1}-\sqrt{x^2-2x-1}\right)$.

a. $\displaystyle \lim_{x\to \pi/2}\sec x-\operatorname{tg}(x)$
:::
:::

:::

:::{.callout-tip collapse="true"}
## Solución
a. $\displaystyle \lim_{x\to 2} \dfrac{x^2+x-6}{x-2} =  \lim_{x\to 2} \dfrac{(x+3)(x-2)}{x-2} = \lim_{x\to 2} \frac{x+3}{1}=5$.

a. 

    \begin{align*}
    \lim_{x\to 1}\dfrac{x^3-3x+2}{x^4-4x+3} &= \lim_{x\to 1}\dfrac{(x-1)^2(x+2)}{(x-1)^2(x^2+2x+3)}\\  
    &= \lim_{x\to 1}\dfrac{(x+2)}{(x^2+2x+3)}= \frac{3}{6}=\frac{1}{2}.
    \end{align*}

a. Aplicando la propiedad trigonométrica $\operatorname{sen}(x+a)=\operatorname{sen}(x)\cos(a)+\cos(x)\operatorname{sen}(a)$, se tiene

    \begin{align*}
    \lim_{x\to 0}\frac{\operatorname{sen}(x+a)-\operatorname{sen}(a)}{x} &= \lim_{x\to 0}\frac{\operatorname{sen}(x)\cos(a)+\cos(x)\operatorname{sen}(a)-\operatorname{sen}(a)}{x} \\ 
    &= \lim_{x\to 0}\frac{\operatorname{sen}(x)\cos(a)-\operatorname{sen}(a)(1-\cos(x))}{x} \\ 
    &= \cos(a)\lim_{x\to 0}\frac{\operatorname{sen}(x)}{x}-\operatorname{sen}(a)\lim_{x\to 0}\frac{1-\cos(x)}{x}\\
    & = \cos(a)\cdot 1-\operatorname{sen}(a)\cdot 0= \cos(a).
    \end{align*}


a. Como $x<e^x$ $\forall x>0$, se tiene que 

    $$
    0<\frac{x}{2}<e^{x/2} \Rightarrow 0< x < 2e^{x/2} \Rightarrow  0< \frac{x}{e^{2x}} < \frac{2e^{x/2}}{e^{2x}} = \frac{2}{e^{3x/2}},$$

    de modo que, como $\lim_{x\to\infty}\frac{2}{e^{3x/2}}=0$,  aplicando el teorema de compresión de funciones se tiene que $\lim_{x\to\infty} \frac{x}{e^{2x}}=0$.

    Usando este resultado se tiene,

    $$\lim_{x\to\infty}\dfrac{x^2-3x+2}{e^{2x}} = \lim_{x\to\infty}\dfrac{x^2}{e^{2x}}-3\lim_{x\to\infty} \frac{x}{e^{2x}} + \lim_{x\to\infty} \frac{2}{e^{2x}} = 0.
    $$

a. Cuando $x\to\infty$, $\frac{\log(x^2-1)}{x+2}\to \frac{\infty}{\infty}$ que es indeterminado. Aplicando la regla de L'Hôpital se tiene,

    $$
    \lim_{x\to\infty}\dfrac{\log(x^2-1)}{x+2} =\lim_{x\to\infty}\frac{1/x}{1} =0.
    $$

a. $\displaystyle \lim_{x\to 1}\frac{\log(1/x)}{\operatorname{tg}(x+\frac{\pi}{2})} = \frac{\lim_{x\to 1}\log(1/x)}{\lim_{x\to 1}\operatorname{tg}(x+\frac{\pi}{2})} = \frac{\log(1)}{\operatorname{tg}(1+\frac{\pi}{2})}=0$

a. $x^n-a^n = (x-a)(x^{n-1}+ax^{n-2}+a^2x^{n-3}+\cdots + a^{n-2}x+a^{n-1}$ $\forall n\in\mathbb{N}$, $n\geq 2$. Así pues, 

    \begin{align*}
    \lim_{x\to a}\dfrac{x^n-a^n}{x-a} &= \lim_{x\to a}\frac{(x-a)(x^{n-1}+ax^{n-2}+\cdots + a^{n-2}x+a^{n-1}}{x-a} \\ 
    &= \lim_{x\to a} x^{n-1}+ax^{n-2}+\cdots + a^{n-2}x+a^{n-1}\\  
    &= a^{n-1}+\stackrel{n}{\dots}+a^{n-1} = na^{n-1}
    \end{align*}

a. Cuando $x\to 1$ $\frac{\sqrt[n]{x}-1}{\sqrt[m]{x}-1}\to \frac{0}{0}$ que es indeterminado. Aplicando la regla de L'Hôpital se tiene 

    \begin{align*}
    \lim_{x\to 1}\frac{\sqrt[n]{x}-1}{\sqrt[m]{x}-1} &= \lim_{x\to 1}\frac{x^{1/n}-1}{x^{1/m}-1} = \lim_{x\to 1}\frac{\frac{1}{n}x^{1/n-1}}{\frac{1}{m}x^{1/m-1}}\\  
    &= \lim_{x\to 1}\frac{mx^{1/n-1}}{nx^{1/m-1}} = \frac{m}{n}.
    \end{align*}

a. Como $\operatorname{sen}(x)\approx\operatorname{tg}(x)\approx x$ cuando $x\to 0$, se tiene

    $$
    \lim_{x\to 0}\frac{\operatorname{tg}(x)-\operatorname{sen}(x)}{x^3} = \lim_{x\to 0}\frac{x-x}{x^3} = \lim_{x\to 0}\frac{0}{x^3} = 0.
    $$

a. Aplicando propiedades trigonométricas se tiene

    \begin{align*}
    \lim_{x\to \pi/4}\frac{\operatorname{sen}(x)-\cos(x)}{1-\operatorname{tg}(x)} &= \lim_{x\to \pi/4}\frac{\operatorname{sen}(x)-\cos x}{1-\frac{\operatorname{sen}(x)}{\cos(x)}}\\ 
    & = \lim_{x\to \pi/4}\frac{\operatorname{sen}(x)-\cos x}{\frac{\cos(x)-\operatorname{sen}(x)}{\cos(x)}}\\ 
    & = \lim_{x\to \pi/4} -\cos(x) = \frac{-\sqrt{2}}{2}.
    \end{align*}

a. Cuando $x\to 0$, $x^2e^{1/x^2}\to 0\cdot \infty$, que es indeterminado. Transformando la indeterminación en una de tipo cociente y aplicando la regla de L'Hôpital se tiene

    \begin{align*}
    \lim_{x\to 0}x^2e^{1/x^2} &= \lim_{x\to 0}\frac{e^{1/x^2}}{1/x^2} = \lim_{x\to 0}\frac{e^{1/x^2}\frac{-2}{x^3}}{-2/x^3} = \lim_{x\to 0} e^{1/x^2} =\infty.
    \end{align*}

a. Cuando $x\to 0$, $\ln(1+x)\approx x$, de manera que

    \begin{align*}
    \lim_{x\to 0}\left(1+x\right)^{1/x} &= \lim_{x\to 0}e^{\ln(\left(1+x\right)^{1/x})} = e^{\lim_{x\to 0}\frac{\ln(1+x)}{x}}\\  
    &= e^{\lim_{x\to 0}\frac{x}{x}} = e^{\lim_{x\to 0}1} = e^1 = e.
    \end{align*}

a. Cuando $x\to\infty$ $\sqrt[x]{x^2}=x^{2/x}\to \infty^0$, que es intedeterminado. Transformando la indeterminación en una de tipo cociente y aplicando la regla de L'Hôpital, se tiene

    \begin{align*}
    \lim_{x\to \infty} \sqrt[x]{x^2} 
    &= \lim_{x\to \infty} x^{2/x} = \lim_{x\to \infty} e^{\ln(x^{2/x})}\\
    & = e^{\lim_{x\to \infty} \frac{2\ln(x)}{x}} = e^{\lim_{x\to \infty} \frac{\frac{2}{x}}{1}} = 1.
    \end{align*}

a. $\displaystyle \lim_{x\to 0}\left(\dfrac{1}{x}\right)^{\operatorname{tg}(x)}$

a. $\displaystyle \lim_{x\to 0}(\cos x)^{1/\operatorname{sen}(x)}$

a. $\displaystyle \lim_{x\to 0}\dfrac{6}{4+e^{-1/x}}$

a. $\displaystyle \lim_{x\to \infty}\left(\sqrt{x^2+x+1}-\sqrt{x^2-2x-1}\right)$.

a. $\displaystyle \lim_{x\to \pi/2}\sec x-\operatorname{tg}(x)$
:::

:::{#exr-ejemplos-limites-laterales}
$\star$
Dar ejemplo de funciones que cumplan las siguientes condiciones:

a. $\lim_{x\to 0}f(x)=+\infty$ y $\lim_{x\to \infty}f(x)=0$.

b. $\lim_{x\to 3^+}f(x)=+\infty$, $\lim_{x\to 3^-}f(x)=-\infty$ y $\lim_{x\to \infty}f(x)=1$.

c. $\lim_{x\to 0^+}f(x)=+\infty$ y $\lim_{x\to \infty}f(x)=-\infty$
:::

:::{.callout-tip collapse="true"}
## Solución
a. $f(x)=\frac{1}{x^2}$.

a. $g(x)=\frac{x}{x-3}$.

a. $h(x)=-\ln(x)$.
:::

:::{#exr-limite-laterales}
$\star$
Sea $g(x)=e^{1/x}$ $\forall x\neq 0$. Demostrar que no existe el límite de $g$ en $0$.
:::

:::{.callout-tip collapse="true"}
## Solución
Basta con probar que el límite lateral por la derecha no existe. Para ello, tomando la sucesión de términos positivos $\left(\frac{1}{n}\right)_1^\infty$ que converge a $0$, se tiene que

$$
\lim_{n\to\infty}g\left(\frac{1}{n}\right) = \lim_{n\to\infty}e^{\frac{1}{1/n}} =  \lim_{n\to\infty}e^n = \infty.
$$
Así pues, según el criterio de las sucesiones convergentes, no existe el límite por la derecha de $g$ en $0$, y por tanto tampoco existe el límite.
:::

:::{#exr-limites-laterales}
Dada la función 

$$
f(x)=\begin{cases}
x^2, \mbox{si } x\leq 1,\\ 
ax-1, \mbox{si } x>1
\end{cases}
$$

con $a\in\mathbb{R}$. ¿Para que valor de $a$ existe el límite de $f$ en $1$?
:::

:::{.callout-tip collapse="true"}
## Solución
Los límtes laterales en 1 valen 

$\lim_{x\to 1^-} f(x) = \lim_{x\to 1^-} x^2 = 1^2 = 1.$
$\lim_{x\to 1^+} f(x) = \lim_{x\to 1^+} ax-1 = a-1.$

Para que exista el límite de $f$ en $1$ debe ser $\lim_{x\to 1^-}f(x)=\lim_{x\to 1^+}f(x)$, es decir, $1=a-1$, luego debe ser $a=2$.
:::

:::{#exr-limites-laterales-2}
$\star$
Calcular los límites laterales de la función
$f(x)=\dfrac{1}{1+e^{\frac{1}{1-x}}}$ en el punto $x=1$. ¿Existe el límite en ese punto?
:::

:::{.callout-tip collapse="true"}
## Solución
\begin{align*}
\lim_{x\to 1^-}f(x) &= \lim_{x\to 1^-} \frac{1}{1+e^{\frac{1}{1-x}}} = \frac{1}{1+\lim_{x\to 1^-}e^\frac{1}{1-x}}\\ 
&= \frac{1}{1+e^{\lim_{x\to 1^-}\frac{1}{1-x}}} =  \frac{1}{1+e^\infty} = \frac{1}{1+\infty} = 0.
\end{align*}

\begin{align*}
\lim_{x\to 1^+}f(x) &= \lim_{x\to 1^+} \frac{1}{1+e^{\frac{1}{1-x}}} = \frac{1}{1+\lim_{x\to 1^+}e^\frac{1}{1-x}}\\ 
&= \frac{1}{1+e^{\lim_{x\to 1^+}\frac{1}{1-x}}} =  \frac{1}{1+e^{-\infty}} = \frac{1}{1+0} = 1.
\end{align*}

Como los límites laterales son distintos, no existe el límite de $f$ en $1$.
:::

:::{#exr-asintotas}
$\star$
Calcular las asíntotas de las siguientes funciones:

:::: {.columns}
::: {.column}
a. $f(x)=(1-x)e^x$

a. $g(x)=xe^{1/x}$

a. $h(x)=2x^2-\ln(x)$
:::

::: {.column}
d. $i(x)=\log(x^2+3x+2)$

a. $j(x)=\dfrac{x^3}{(x+1)^2}$

a. $k(x)=\cos x-\log(\cos x)$
:::
:::
:::

:::{.callout-tip collapse="true"}
## Solución
a. $f$ está definida en $\mathbb{R}$, así que no tiene asíntotas verticales. 

    Para ver si $f$ tiene asíntotas horizontales estudiamos los límites en el infinito. Cuando $x\to -\infty$ $(1-x)e^x\to -\infty\cdot 0$ que es indeterminado. Transformando la indeterminación en una de tipo cociente

    \begin{align*}
    \lim_{x\to -\infty}(1-x)e^x &= \lim_{x\to -\infty}\frac{1-x}{e^-x} = \lim_{x\to -\infty}\frac{1}{e^{-x}}- \lim_{x\to -\infty} \frac{-x}{e^{-x}}\\ 
    &= 0 -\lim_{x\to -\infty}\frac{-x}{e^{-x}}.
    \end{align*}

    Por otro lado $\forall x<0$ se cumple que $e^{-x}\geq x^2$ $0\leq \frac{-x}{e^{-x}}\leq \frac{-x}{x^2}=\frac{1}{x}$, y como $\lim_{x\to -\infty}\frac{-1}{x}=0$, por el teorema de compresión de funciones se tiene que $\lim_{x\to -\infty}\frac{-x}{e^{-x}} = 0$.

    Así pues, $y=0$ es una asíntota horizontal en $-\infty$.

    Por otro lado, $\lim_{x\to \infty}(1-x)e^x = -\infty*\infty = -\infty$, de modo que no hay asíntota horizontal en $\infty$.

    Finalmente para ver si $f$ tiene asíntotas oblicuas, estudiamos estudiamos el límite de $f(x)/x$ en $\infty$ (en $-\infty$ no puede haber asíntota oblicua porque existe una horizontal).

    $$
    \lim_{x\to \infty}\frac{(1-x)e^x}{x} = \lim_{x\to \infty} \frac{1-x}{x}\lim_{x\to \infty}e^x = -1\cdot \infty = -\infty.
    $$

    Por tanto, tampoco existe asíntota oblicua en $\infty$.

a. $g$ está definida en $\mathbb{R}\setminus \{0\}$, así que, el único punto donde pueden existir asíntotas verticales es $x=0$. Calculando los límites laterales se tiene

    \begin{align*}
    \lim_{x\to 0^-} xe^{1/x} &= \lim_{x\to 0^-}x \lim_{x\to 0^-}e^{1/x} = 0\cdot e^-\infty = 0\cdot 0 = 0.\\ 
    \lim_{x\to 0^+} xe^{1/x} &= \lim_{x\to 0^+}\frac{e^{1/x}}{1/x} = \lim_{x\to 0^+}\frac{(e^{1/x})'}{(1/x)'} \tag{\small L'Hôpital}\\ 
    &= \lim_{x\to 0^+}\frac{e^{1/x}(1/x)'}{(1/x)'} = \lim_{x\to 0^+}e^{1/x} = \infty. 
    \end{align*}
    
    Por tanto, $g$ tiene asíntota vertical $x=0$ por la derecha, pero no por la izquierda.

    Para ver si $g$ tiene asíntotas horizontales estudiamos los límites en el infinito. 

    \begin{align*}
    \lim_{x\to -\infty}xe^{1/x} &= \lim_{x\to -\infty}x \lim_{x\to -\infty}e^{1/x} = \infty * 1 = \infty.\\ 
    \lim_{x\to \infty}xe^{1/x} &= \lim_{x\to \infty}x \lim_{x\to \infty}e^{1/x} = \infty * 1 = \infty.
    \end{align*}

    Así pues, ambos límites no existen y, por tanto, $g$ no tiene asíntotas horizontales.

    Finalmente para ver si $f$ tiene asíntotas oblicuas, estudiamos estudiamos el límite de $f(x)/x$ en $\pm\infty$.

    $$
    \lim_{x\to -\infty}\frac{xe^{1/x}}{x} = \lim_{x\to -\infty} e^{1/x} = e^0 =1.
    $$

    Luego, existe una asíntota oblicua en $-\infty$ con pendiente $1$. Para ver el término independiente de la asíntota calculamos el límite de $f(x)-1\cdot x$ en $-\infty$.

    \begin{align*}
    \lim_{x\to -\infty}xe^{1/x}-x &= \lim_{x\to -\infty} x(e^{1/x}-1) = \lim_{x\to -\infty} \frac{e^{1/x}-1}{1/x} \\ 
    &= \lim_{x\to -\infty} \frac{(e^{1/x}-1)'}{(1/x)'} \tag{\small L'Hôpital}\\ 
    &= \lim_{x\to -\infty} \frac{e^{1/x} (1/x)'}{(1/x)'} = \lim_{x\to -\infty} e^{1/x} = 1.
    \end{align*}
  
    Así pues, $g$ tiene una asíntota oblicua $y=x+1$ en $-\infty$. Del mismo modo se puede probar que esta misma recta es asíntota oblicua en $\infty$.
:::



:::{#exr-acuifero}
$\star$
Mediante simulación por ordenador se ha podido cuantificar la cantidad de agua almacenada en un
acuífero en función del tiempo, $m(t)$, en millones de metros cúbicos, y el tiempo $t$ en años transcurridos
desde el instante en el que se ha hecho la simulación, teniendo en cuenta que la ecuación sólo tiene
sentido para $t>0$:

$$
m(t) = 10 + \frac{\sqrt{t}}{e^t}
$$

¿Qué cantidad de agua almacenada habrá en el acuífero asintóticamente?
:::

:::{.callout-tip collapse="true"}
## Solución
Cuando $t\to\infty $\frac{\sqrt{t}}{e^t}\to \frac{\infty}{\infty}$ que es indeterminado. Aplicando la regla de L'Hôpital se tiene

$$
\lim_{t\to \infty} 10 + \frac{\sqrt{t}}{e^t} = 10 + \lim_{t\to \infty} \frac{\sqrt{t}}{e^t} = \\lim_{t\to \infty}\frac{1}{2\sqrt(t)e^t} = 10.
$$

Por tanto el volumen del lato tiende asintóticamente a 10 millones de metros cúbicos.
:::

:::{#exr-cosecha}
$\star$
La cosecha de trigo de una plantación (en toneladas) depende de la cantidad de abono $x$ según la función $f(x)=T(1-\frac{1}{2}e^{-kx})$, donde $T$ es la extensión del terreno (en hectáreas) y $k$ es la proporción de humedad. ¿Para qué cantidad de abono se conseguiría una cosecha de $T$ toneladas de trigo? 
:::

:::{.callout-tip collapse="true"}
## Solución
Como $k>0$ se tiene $\frac{1}{2}e^{-kx} = \frac{1}{2e^{kx}} < 1$ $\forall x>0$, de manera que $f(x)<T$ $\forall x>0$. Si calculamos ahora el límite en infinito se tiene

$$\lim_{x\to \infty} T(1-\frac{1}{2}e^{-kx}) = T(1-\lim_{x\to \infty}\frac{1}{2e^{kx}}) = T(1-0) = T.
$$ 

De modo la cantidad de trigo cosechada tiene asintóticamente a $T$, pero al ser menor que $T$, nunca llegará a valer $T$.
:::

:::{#exr-limites-funciones-acotadas}
Sea $f:(a,b)\to \mathbb{R}$ una función creciente. Demostrar lo siguiente:

a. Si $f$ está acotada superiormente, entonces existe $\lim_{x\to b^-}f(x)$.
b. Si $f$ no está acotada superiormente, entonces $\lim_{x\to b^-}f(x)=\infty$.
:::

<!-- 
:::{#exr-limite-e1}
Demostrar que $\lim_{x\to \infty} \left(1+\dfrac{1}{x}\rifht)^x = e$ usando el [teorema de compresión de funciones](https://aprendeconalf.es/analisis-manual/limites.html#thm-compresión-funciones). 
:::

:::{#exr-limite-e2}
Demostrar que $\lim_{x\to 0} (1+x)^{1/x} = e$.
::: -->