---
title: prueba
lang: es
---

:::{#exr-superficie-deposito}
Un depósito metálico tiene la forma del elipsoide que se obtiene al rotar la elipse $\frac{x^2}{4}+y^2=1$ alrededor del eje $x$, con $x$ en metros. Calcular la cantidad de chapa metálica necesaria para construir el depósito. ¿Y si el depósito se construye rotando la elipse alrededor del eje $y$?
:::

:::{.callout-tip collapse="true"}
## Solución
Para averiguar la cantidad de chapa necesaria para construir el depósito tenemos que calcular el área de la superficie del depósito. 

De la ecuación de la elipse se tiene

$$
\frac{x^2}{4}+y^2=1 \Leftrightarrow y^2 = 1-\frac{x^2}{4} \Leftrightarrow y = \pm \sqrt{1-\frac{x^2}{4}},
$$

de manera que el depósito se genera al rotar alrededor del eje $x$ la gráfica de la función $f(x) = \sqrt{1-\frac{x^2}{4}}$ en el intervalo $[-2,2]$.

El [área de la superficie del sólido de revolución](https://aprendeconalf.es/analisis-manual/08-integrales.html#c%C3%A1lculo-de-superficies-de-s%C3%B3lidos-de-revoluci%C3%B3n) que se obtiene al rotar la gráfica de $f$ alrededor del eje $x$ en el intervalo $[a,b]$ viene dado por la integral

$$
\int_a^b 2\pi f(x) \sqrt{1+f'(x)^2}\,dx
$$

Como 

$$
f'(x) = \frac{-x}{4\sqrt{1-\frac{x^2}{4}}},
$$

sustituyendo en la integral anterior se tiene

\begin{align*}
\int_{-2}^2 2\pi f(x) \sqrt{1+f'(x)^2}\,dx
&= 2\pi \int_{-2}^2 \sqrt{1-\frac{x^2}{4}}\sqrt{1+ \left(\frac{-x}{4\sqrt{1-\frac{x^2}{4}}}\right)^2}\,dx \\
&= 2\pi \int_{-2}^2 \sqrt{1-\frac{x^2}{4}}\sqrt{1+ \frac{x^2}{16\left(1-\frac{x^2}{4}\right)}}\,dx \\
&= 2\pi \int_{-2}^2 \sqrt{\left(1-\frac{x^2}{4}\right)\left(1+ \frac{x^2}{16\left(1-\frac{x^2}{4}\right)}\right)}\,dx \\
&= 2\pi \int_{-2}^2 \sqrt{1-\frac{x^2}{4}+\frac{x^2}{16}}\,dx \\
&= 2\pi \int_{-2}^2 \sqrt{1-\frac{3x^2}{16}}\,dx \\
&= 2\pi \int_{-2}^2 \frac{1}{4}\sqrt{16-3x^2}\,dx \\
&= \frac{\pi}{2} \int_{-2}^2 \sqrt{4^2-(\sqrt{3}x)^2}\,dx \\
&= \frac{\pi}{2} \int_{\operatorname{arcsen}(-\sqrt{3}/2)}^{\operatorname{arcsen}(\sqrt{3}/2)} \sqrt{4^2-4^2\operatorname{sen(\theta)^2}}\frac{4}{\sqrt{3}}\cos(\theta)\,d\theta \tag{1} \\
&= \frac{\pi}{2} \int_{\operatorname{arcsen}(-\sqrt{3}/2)}^{\operatorname{arcsen}(\sqrt{3}/2)} 4\cos(\theta)\frac{4}{\sqrt{3}}\cos(\theta)\,d\theta \\
&= \frac{8\pi}{\sqrt{3}} \int_{\operatorname{arcsen}(-\sqrt{3}/2)}^{\operatorname{arcsen}(\sqrt{3}/2)} \cos(\theta)^2\,d\theta \\
&= \frac{8\pi}{\sqrt{3}} \int_{\operatorname{arcsen}(-\sqrt{3}/2)}^{\operatorname{arcsen}(\sqrt{3}/2)} \frac{1+\cos(2\theta)}{2}\,d\theta \\
&= \frac{8\pi}{\sqrt{3}}\left[\frac{\theta}{2}+\frac{1}{4}\operatorname{sen}(2\theta)\right]_{\operatorname{arcsen}(-\sqrt{3}/2)}^{\operatorname{arcsen}(\sqrt{3}/2)} \\
&= \frac{8\pi}{\sqrt{3}}\left[\frac{\theta}{2}+\frac{1}{2}\operatorname{sen}(\theta)\cos(\theta)\right]_{\operatorname{arcsen}(-\sqrt{3}/2)}^{\operatorname{arcsen}(\sqrt{3}/2)} \\
&=\frac{8\pi}{\sqrt{3}}\left(\frac{1}{2}\operatorname{arcsen}(\sqrt{3}/2)+\frac{1}{2}\operatorname{sen}(\operatorname{arcsen}(\sqrt{3}/2))\cos(\operatorname{arcsen}(\sqrt{3}/2)) - \frac{1}{2}\operatorname{arcsen}(-\sqrt{3}/2) - \frac{1}{2}\operatorname{sen}(\operatorname{arcsen}(-\sqrt{3}/2))\cos(\operatorname{arcsen}(-\sqrt{3}/2))\right)\\
&=\frac{8\pi}{\sqrt{3}}\left(\operatorname{arcsen}(\sqrt{3}/2)+\frac{\sqrt{3}}{4}\right)\\
&= \frac{8\pi^2}{3\sqrt{3}}2\pi
\approx 21.4784  \mbox{ m}^2.
\end{align*}

(1) Cambio $x = \frac{4}{\sqrt{3}\operatorname{sen}(\theta)}$.
:::

:::{#exr-superficie-toro}
Calcular el área de la superficie de este [toro](https://www.geogebra.org/m/wy2uquqc) obtenido al rotar la circunferencia de ecuación $(x-2)^2+y^2=1$ alrededor del eje $y$. Calcular a continuación la superficie de un toro de radio mayor $R$ y radio menor $r$.
:::

:::{.callout-tip collapse="true"}
## Solución
Calcularemos directamente la superficie de un toro con radio mayor $R$ y radio menor $r$, que tiene ecuación 

$$
(x-R)^2+y^2=r^2 \Leftrightarrow y^2 = r^2-(x-R)^2 \Leftrightarrow y=\pm \sqrt{r^2-(x-R)^2},
$$

donde la rama positiva corresponde al semi-toro positivo y la negativa al semi-toro negativo. Por simetría, para calcular el área de la superficie del toro basta con calcular el área de las superficie del semi-toro positivo y multiplicarla por 2. El [área de la superficie del sólido de revolución](https://aprendeconalf.es/analisis-manual/08-integrales.html#c%C3%A1lculo-de-superficies-de-s%C3%B3lidos-de-revoluci%C3%B3n) que se obtiene al rotar la gráfica de una función $f$ alrededor del eje $y$ en un intervalo $[a,b]$ viene dado por la integral

$$
\int_a^b 2\pi x \sqrt{1+f'(x)^2}\,dx
$$

En este caso, tomando $f(x)=\sqrt{r^2-(x-R)^2}$, se tiene que 

$$
f'(x) = \frac{R-x}{\sqrt{r^2-(x-R)^2}} = \frac{R-x}{f(x)}
$$

y

\begin{align*}
\sqrt{1+f'(x)^2} 
&= \sqrt{1+\left(\frac{R-x}{f(x)}\right)^2}
= \sqrt{\frac{f(x)^2+(x-R)^2}{f(x)^2}} \\
&= \sqrt{\frac{r^2}{f(x)^2}}
= \frac{r}{f(x)}
= \frac{r}{\sqrt{r^2-(x-R)^2}}
\end{align*}

Así pues, sustituyendo en la integral anterior se tiene

\begin{align*}
\int_{R-r}^{R+r} 2\pi x \sqrt{1+f'(x)^2}\,dx 
&= \int_{R-r}^{R+r} 2\pi x \frac{r}{\sqrt{r^2-(x-R)^2}}\,dx \\
&= 2\pi r \int_{R-r}^{R+r} \frac{x}{\sqrt{r^2-(x-R)^2}}\,dx \\
&= 2\pi r \int_{-1}^1 \frac{ur+R}{\sqrt{r^2-(ur)^2}}r\,du \tag{Cambio $u=\frac{x-R}{r}$}\\
&= 2\pi r \int_{-1}^1 \frac{ur+R}{\sqrt{1-u^2}}\,du \\
&= 2\pi r \left(\int_{-1}^1 \frac{ur}{\sqrt{1-u^2}}\,du + \int_{-1}^1 \frac{R}{\sqrt{1-u^2}}\right) \\
&= 2\pi r \left(r[-\sqrt{1-u^2}]_{-1}^1 + R[\operatorname{arcsen}(u)]_{-1}^1\right) \\
&= 2\pi r R\left(\frac{\pi}{2}+\frac{\pi}{2}\right)
= 2\pi^2 r R.
\end{align*}

Por tanto, el área de las superficie del toro es el doble, $4\pi^2 r R$.
:::